#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDantist
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Dentists")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    partial void InsertАктВыполненныхРабот(АктВыполненныхРабот instance);
    partial void UpdateАктВыполненныхРабот(АктВыполненныхРабот instance);
    partial void DeleteАктВыполненныхРабот(АктВыполненныхРабот instance);
    partial void InsertДоговор(Договор instance);
    partial void UpdateДоговор(Договор instance);
    partial void DeleteДоговор(Договор instance);
    partial void InsertУслугиПоДоговору(УслугиПоДоговору instance);
    partial void UpdateУслугиПоДоговору(УслугиПоДоговору instance);
    partial void DeleteУслугиПоДоговору(УслугиПоДоговору instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::ControlDantist.Properties.Settings.Default.DentistsConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<АктВыполненныхРабот> АктВыполненныхРабот
		{
			get
			{
				return this.GetTable<АктВыполненныхРабот>();
			}
		}
		
		public System.Data.Linq.Table<Договор> Договор
		{
			get
			{
				return this.GetTable<Договор>();
			}
		}
		
		public System.Data.Linq.Table<УслугиПоДоговору> УслугиПоДоговору
		{
			get
			{
				return this.GetTable<УслугиПоДоговору>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class АктВыполненныхРабот : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_акт;
		
		private int _id_договор;
		
		private string _НомерАкта;
		
		private System.DateTime _ДатаПодписания;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_актChanging(int value);
    partial void Onid_актChanged();
    partial void Onid_договорChanging(int value);
    partial void Onid_договорChanged();
    partial void OnНомерАктаChanging(string value);
    partial void OnНомерАктаChanged();
    partial void OnДатаПодписанияChanging(System.DateTime value);
    partial void OnДатаПодписанияChanged();
    #endregion
		
		public АктВыполненныхРабот()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_акт", IsPrimaryKey=true)]
		public int id_акт
		{
			get
			{
				return this._id_акт;
			}
			set
			{
				if ((this._id_акт != value))
				{
					this.Onid_актChanging(value);
					this.SendPropertyChanging();
					this._id_акт = value;
					this.SendPropertyChanged("id_акт");
					this.Onid_актChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_договор")]
		public int id_договор
		{
			get
			{
				return this._id_договор;
			}
			set
			{
				if ((this._id_договор != value))
				{
					this.Onid_договорChanging(value);
					this.SendPropertyChanging();
					this._id_договор = value;
					this.SendPropertyChanged("id_договор");
					this.Onid_договорChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_НомерАкта", CanBeNull=false)]
		public string НомерАкта
		{
			get
			{
				return this._НомерАкта;
			}
			set
			{
				if ((this._НомерАкта != value))
				{
					this.OnНомерАктаChanging(value);
					this.SendPropertyChanging();
					this._НомерАкта = value;
					this.SendPropertyChanged("НомерАкта");
					this.OnНомерАктаChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ДатаПодписания")]
		public System.DateTime ДатаПодписания
		{
			get
			{
				return this._ДатаПодписания;
			}
			set
			{
				if ((this._ДатаПодписания != value))
				{
					this.OnДатаПодписанияChanging(value);
					this.SendPropertyChanging();
					this._ДатаПодписания = value;
					this.SendPropertyChanged("ДатаПодписания");
					this.OnДатаПодписанияChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Договор")]
	public partial class Договор : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_договор;
		
		private string _НомерДоговора;
		
		private System.Nullable<System.DateTime> _ДатаДоговора;
		
		private System.Nullable<System.DateTime> _ДатаАктаВыполненныхРабот;
		
		private System.Nullable<decimal> _СуммаАктаВыполненныхРабот;
		
		private System.Nullable<int> _id_льготнаяКатегория;
		
		private System.Nullable<int> _id_поликлинника;
		
		private string _Примечание;
		
		private System.Nullable<int> _id_комитет;
		
		private System.Nullable<bool> _ФлагНаличияДоговора;
		
		private System.Nullable<bool> _ФлагНаличияАкта;
		
		private System.Nullable<int> _id_льготник;
		
		private string _ФлагДопСоглашения;
		
		private System.Nullable<bool> _флагСРН;
		
		private System.Nullable<bool> _флагУслуги;
		
		private System.Nullable<System.DateTime> _датаВозврата;
		
		private System.Nullable<System.DateTime> _ДатаЗаписиДоговора;
		
		private System.Nullable<bool> _ФлагПроверки;
		
		private string _НомерРеестра;
		
		private System.Nullable<System.DateTime> _ДатаРеестра;
		
		private string _НомерСчётФактрура;
		
		private System.Nullable<System.DateTime> _ДатаСчётФактура;
		
		private string _logWrite;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_договорChanging(int value);
    partial void Onid_договорChanged();
    partial void OnНомерДоговораChanging(string value);
    partial void OnНомерДоговораChanged();
    partial void OnДатаДоговораChanging(System.Nullable<System.DateTime> value);
    partial void OnДатаДоговораChanged();
    partial void OnДатаАктаВыполненныхРаботChanging(System.Nullable<System.DateTime> value);
    partial void OnДатаАктаВыполненныхРаботChanged();
    partial void OnСуммаАктаВыполненныхРаботChanging(System.Nullable<decimal> value);
    partial void OnСуммаАктаВыполненныхРаботChanged();
    partial void Onid_льготнаяКатегорияChanging(System.Nullable<int> value);
    partial void Onid_льготнаяКатегорияChanged();
    partial void Onid_поликлинникаChanging(System.Nullable<int> value);
    partial void Onid_поликлинникаChanged();
    partial void OnПримечаниеChanging(string value);
    partial void OnПримечаниеChanged();
    partial void Onid_комитетChanging(System.Nullable<int> value);
    partial void Onid_комитетChanged();
    partial void OnФлагНаличияДоговораChanging(System.Nullable<bool> value);
    partial void OnФлагНаличияДоговораChanged();
    partial void OnФлагНаличияАктаChanging(System.Nullable<bool> value);
    partial void OnФлагНаличияАктаChanged();
    partial void Onid_льготникChanging(System.Nullable<int> value);
    partial void Onid_льготникChanged();
    partial void OnФлагДопСоглашенияChanging(string value);
    partial void OnФлагДопСоглашенияChanged();
    partial void OnфлагСРНChanging(System.Nullable<bool> value);
    partial void OnфлагСРНChanged();
    partial void OnфлагУслугиChanging(System.Nullable<bool> value);
    partial void OnфлагУслугиChanged();
    partial void OnдатаВозвратаChanging(System.Nullable<System.DateTime> value);
    partial void OnдатаВозвратаChanged();
    partial void OnДатаЗаписиДоговораChanging(System.Nullable<System.DateTime> value);
    partial void OnДатаЗаписиДоговораChanged();
    partial void OnФлагПроверкиChanging(System.Nullable<bool> value);
    partial void OnФлагПроверкиChanged();
    partial void OnНомерРеестраChanging(string value);
    partial void OnНомерРеестраChanged();
    partial void OnДатаРеестраChanging(System.Nullable<System.DateTime> value);
    partial void OnДатаРеестраChanged();
    partial void OnНомерСчётФактрураChanging(string value);
    partial void OnНомерСчётФактрураChanged();
    partial void OnДатаСчётФактураChanging(System.Nullable<System.DateTime> value);
    partial void OnДатаСчётФактураChanged();
    partial void OnlogWriteChanging(string value);
    partial void OnlogWriteChanged();
    #endregion
		
		public Договор()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_договор", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_договор
		{
			get
			{
				return this._id_договор;
			}
			set
			{
				if ((this._id_договор != value))
				{
					this.Onid_договорChanging(value);
					this.SendPropertyChanging();
					this._id_договор = value;
					this.SendPropertyChanged("id_договор");
					this.Onid_договорChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_НомерДоговора", DbType="NChar(100)")]
		public string НомерДоговора
		{
			get
			{
				return this._НомерДоговора;
			}
			set
			{
				if ((this._НомерДоговора != value))
				{
					this.OnНомерДоговораChanging(value);
					this.SendPropertyChanging();
					this._НомерДоговора = value;
					this.SendPropertyChanged("НомерДоговора");
					this.OnНомерДоговораChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ДатаДоговора", DbType="DateTime")]
		public System.Nullable<System.DateTime> ДатаДоговора
		{
			get
			{
				return this._ДатаДоговора;
			}
			set
			{
				if ((this._ДатаДоговора != value))
				{
					this.OnДатаДоговораChanging(value);
					this.SendPropertyChanging();
					this._ДатаДоговора = value;
					this.SendPropertyChanged("ДатаДоговора");
					this.OnДатаДоговораChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ДатаАктаВыполненныхРабот", DbType="DateTime")]
		public System.Nullable<System.DateTime> ДатаАктаВыполненныхРабот
		{
			get
			{
				return this._ДатаАктаВыполненныхРабот;
			}
			set
			{
				if ((this._ДатаАктаВыполненныхРабот != value))
				{
					this.OnДатаАктаВыполненныхРаботChanging(value);
					this.SendPropertyChanging();
					this._ДатаАктаВыполненныхРабот = value;
					this.SendPropertyChanged("ДатаАктаВыполненныхРабот");
					this.OnДатаАктаВыполненныхРаботChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_СуммаАктаВыполненныхРабот", DbType="Money")]
		public System.Nullable<decimal> СуммаАктаВыполненныхРабот
		{
			get
			{
				return this._СуммаАктаВыполненныхРабот;
			}
			set
			{
				if ((this._СуммаАктаВыполненныхРабот != value))
				{
					this.OnСуммаАктаВыполненныхРаботChanging(value);
					this.SendPropertyChanging();
					this._СуммаАктаВыполненныхРабот = value;
					this.SendPropertyChanged("СуммаАктаВыполненныхРабот");
					this.OnСуммаАктаВыполненныхРаботChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_льготнаяКатегория", DbType="Int")]
		public System.Nullable<int> id_льготнаяКатегория
		{
			get
			{
				return this._id_льготнаяКатегория;
			}
			set
			{
				if ((this._id_льготнаяКатегория != value))
				{
					this.Onid_льготнаяКатегорияChanging(value);
					this.SendPropertyChanging();
					this._id_льготнаяКатегория = value;
					this.SendPropertyChanged("id_льготнаяКатегория");
					this.Onid_льготнаяКатегорияChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_поликлинника", DbType="Int")]
		public System.Nullable<int> id_поликлинника
		{
			get
			{
				return this._id_поликлинника;
			}
			set
			{
				if ((this._id_поликлинника != value))
				{
					this.Onid_поликлинникаChanging(value);
					this.SendPropertyChanging();
					this._id_поликлинника = value;
					this.SendPropertyChanged("id_поликлинника");
					this.Onid_поликлинникаChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Примечание", DbType="NVarChar(300)")]
		public string Примечание
		{
			get
			{
				return this._Примечание;
			}
			set
			{
				if ((this._Примечание != value))
				{
					this.OnПримечаниеChanging(value);
					this.SendPropertyChanging();
					this._Примечание = value;
					this.SendPropertyChanged("Примечание");
					this.OnПримечаниеChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_комитет", DbType="Int")]
		public System.Nullable<int> id_комитет
		{
			get
			{
				return this._id_комитет;
			}
			set
			{
				if ((this._id_комитет != value))
				{
					this.Onid_комитетChanging(value);
					this.SendPropertyChanging();
					this._id_комитет = value;
					this.SendPropertyChanged("id_комитет");
					this.Onid_комитетChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ФлагНаличияДоговора", DbType="Bit")]
		public System.Nullable<bool> ФлагНаличияДоговора
		{
			get
			{
				return this._ФлагНаличияДоговора;
			}
			set
			{
				if ((this._ФлагНаличияДоговора != value))
				{
					this.OnФлагНаличияДоговораChanging(value);
					this.SendPropertyChanging();
					this._ФлагНаличияДоговора = value;
					this.SendPropertyChanged("ФлагНаличияДоговора");
					this.OnФлагНаличияДоговораChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ФлагНаличияАкта", DbType="Bit")]
		public System.Nullable<bool> ФлагНаличияАкта
		{
			get
			{
				return this._ФлагНаличияАкта;
			}
			set
			{
				if ((this._ФлагНаличияАкта != value))
				{
					this.OnФлагНаличияАктаChanging(value);
					this.SendPropertyChanging();
					this._ФлагНаличияАкта = value;
					this.SendPropertyChanged("ФлагНаличияАкта");
					this.OnФлагНаличияАктаChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_льготник", DbType="Int")]
		public System.Nullable<int> id_льготник
		{
			get
			{
				return this._id_льготник;
			}
			set
			{
				if ((this._id_льготник != value))
				{
					this.Onid_льготникChanging(value);
					this.SendPropertyChanging();
					this._id_льготник = value;
					this.SendPropertyChanged("id_льготник");
					this.Onid_льготникChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ФлагДопСоглашения", DbType="NChar(50)")]
		public string ФлагДопСоглашения
		{
			get
			{
				return this._ФлагДопСоглашения;
			}
			set
			{
				if ((this._ФлагДопСоглашения != value))
				{
					this.OnФлагДопСоглашенияChanging(value);
					this.SendPropertyChanging();
					this._ФлагДопСоглашения = value;
					this.SendPropertyChanged("ФлагДопСоглашения");
					this.OnФлагДопСоглашенияChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_флагСРН", DbType="Bit")]
		public System.Nullable<bool> флагСРН
		{
			get
			{
				return this._флагСРН;
			}
			set
			{
				if ((this._флагСРН != value))
				{
					this.OnфлагСРНChanging(value);
					this.SendPropertyChanging();
					this._флагСРН = value;
					this.SendPropertyChanged("флагСРН");
					this.OnфлагСРНChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_флагУслуги", DbType="Bit")]
		public System.Nullable<bool> флагУслуги
		{
			get
			{
				return this._флагУслуги;
			}
			set
			{
				if ((this._флагУслуги != value))
				{
					this.OnфлагУслугиChanging(value);
					this.SendPropertyChanging();
					this._флагУслуги = value;
					this.SendPropertyChanged("флагУслуги");
					this.OnфлагУслугиChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_датаВозврата", DbType="DateTime")]
		public System.Nullable<System.DateTime> датаВозврата
		{
			get
			{
				return this._датаВозврата;
			}
			set
			{
				if ((this._датаВозврата != value))
				{
					this.OnдатаВозвратаChanging(value);
					this.SendPropertyChanging();
					this._датаВозврата = value;
					this.SendPropertyChanged("датаВозврата");
					this.OnдатаВозвратаChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ДатаЗаписиДоговора", DbType="Date")]
		public System.Nullable<System.DateTime> ДатаЗаписиДоговора
		{
			get
			{
				return this._ДатаЗаписиДоговора;
			}
			set
			{
				if ((this._ДатаЗаписиДоговора != value))
				{
					this.OnДатаЗаписиДоговораChanging(value);
					this.SendPropertyChanging();
					this._ДатаЗаписиДоговора = value;
					this.SendPropertyChanged("ДатаЗаписиДоговора");
					this.OnДатаЗаписиДоговораChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ФлагПроверки", DbType="Bit")]
		public System.Nullable<bool> ФлагПроверки
		{
			get
			{
				return this._ФлагПроверки;
			}
			set
			{
				if ((this._ФлагПроверки != value))
				{
					this.OnФлагПроверкиChanging(value);
					this.SendPropertyChanging();
					this._ФлагПроверки = value;
					this.SendPropertyChanged("ФлагПроверки");
					this.OnФлагПроверкиChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_НомерРеестра", DbType="NChar(30)")]
		public string НомерРеестра
		{
			get
			{
				return this._НомерРеестра;
			}
			set
			{
				if ((this._НомерРеестра != value))
				{
					this.OnНомерРеестраChanging(value);
					this.SendPropertyChanging();
					this._НомерРеестра = value;
					this.SendPropertyChanged("НомерРеестра");
					this.OnНомерРеестраChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ДатаРеестра", DbType="Date")]
		public System.Nullable<System.DateTime> ДатаРеестра
		{
			get
			{
				return this._ДатаРеестра;
			}
			set
			{
				if ((this._ДатаРеестра != value))
				{
					this.OnДатаРеестраChanging(value);
					this.SendPropertyChanging();
					this._ДатаРеестра = value;
					this.SendPropertyChanged("ДатаРеестра");
					this.OnДатаРеестраChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_НомерСчётФактрура", DbType="NChar(30)")]
		public string НомерСчётФактрура
		{
			get
			{
				return this._НомерСчётФактрура;
			}
			set
			{
				if ((this._НомерСчётФактрура != value))
				{
					this.OnНомерСчётФактрураChanging(value);
					this.SendPropertyChanging();
					this._НомерСчётФактрура = value;
					this.SendPropertyChanged("НомерСчётФактрура");
					this.OnНомерСчётФактрураChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ДатаСчётФактура", DbType="Date")]
		public System.Nullable<System.DateTime> ДатаСчётФактура
		{
			get
			{
				return this._ДатаСчётФактура;
			}
			set
			{
				if ((this._ДатаСчётФактура != value))
				{
					this.OnДатаСчётФактураChanging(value);
					this.SendPropertyChanging();
					this._ДатаСчётФактура = value;
					this.SendPropertyChanged("ДатаСчётФактура");
					this.OnДатаСчётФактураChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logWrite", DbType="VarChar(150)")]
		public string logWrite
		{
			get
			{
				return this._logWrite;
			}
			set
			{
				if ((this._logWrite != value))
				{
					this.OnlogWriteChanging(value);
					this.SendPropertyChanging();
					this._logWrite = value;
					this.SendPropertyChanged("logWrite");
					this.OnlogWriteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.УслугиПоДоговору")]
	public partial class УслугиПоДоговору : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_услугиДоговор;
		
		private string _НаименованиеУслуги;
		
		private System.Nullable<decimal> _цена;
		
		private System.Nullable<int> _Количество;
		
		private System.Nullable<int> _id_договор;
		
		private string _НомерПоПеречню;
		
		private System.Nullable<decimal> _Сумма;
		
		private System.Nullable<int> _ТехЛист;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_услугиДоговорChanging(int value);
    partial void Onid_услугиДоговорChanged();
    partial void OnНаименованиеУслугиChanging(string value);
    partial void OnНаименованиеУслугиChanged();
    partial void OnценаChanging(System.Nullable<decimal> value);
    partial void OnценаChanged();
    partial void OnКоличествоChanging(System.Nullable<int> value);
    partial void OnКоличествоChanged();
    partial void Onid_договорChanging(System.Nullable<int> value);
    partial void Onid_договорChanged();
    partial void OnНомерПоПеречнюChanging(string value);
    partial void OnНомерПоПеречнюChanged();
    partial void OnСуммаChanging(System.Nullable<decimal> value);
    partial void OnСуммаChanged();
    partial void OnТехЛистChanging(System.Nullable<int> value);
    partial void OnТехЛистChanged();
    #endregion
		
		public УслугиПоДоговору()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_услугиДоговор", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_услугиДоговор
		{
			get
			{
				return this._id_услугиДоговор;
			}
			set
			{
				if ((this._id_услугиДоговор != value))
				{
					this.Onid_услугиДоговорChanging(value);
					this.SendPropertyChanging();
					this._id_услугиДоговор = value;
					this.SendPropertyChanged("id_услугиДоговор");
					this.Onid_услугиДоговорChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_НаименованиеУслуги", DbType="NVarChar(500)")]
		public string НаименованиеУслуги
		{
			get
			{
				return this._НаименованиеУслуги;
			}
			set
			{
				if ((this._НаименованиеУслуги != value))
				{
					this.OnНаименованиеУслугиChanging(value);
					this.SendPropertyChanging();
					this._НаименованиеУслуги = value;
					this.SendPropertyChanged("НаименованиеУслуги");
					this.OnНаименованиеУслугиChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_цена", DbType="Money")]
		public System.Nullable<decimal> цена
		{
			get
			{
				return this._цена;
			}
			set
			{
				if ((this._цена != value))
				{
					this.OnценаChanging(value);
					this.SendPropertyChanging();
					this._цена = value;
					this.SendPropertyChanged("цена");
					this.OnценаChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Количество", DbType="Int")]
		public System.Nullable<int> Количество
		{
			get
			{
				return this._Количество;
			}
			set
			{
				if ((this._Количество != value))
				{
					this.OnКоличествоChanging(value);
					this.SendPropertyChanging();
					this._Количество = value;
					this.SendPropertyChanged("Количество");
					this.OnКоличествоChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_договор", DbType="Int")]
		public System.Nullable<int> id_договор
		{
			get
			{
				return this._id_договор;
			}
			set
			{
				if ((this._id_договор != value))
				{
					this.Onid_договорChanging(value);
					this.SendPropertyChanging();
					this._id_договор = value;
					this.SendPropertyChanged("id_договор");
					this.Onid_договорChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_НомерПоПеречню", DbType="NChar(50)")]
		public string НомерПоПеречню
		{
			get
			{
				return this._НомерПоПеречню;
			}
			set
			{
				if ((this._НомерПоПеречню != value))
				{
					this.OnНомерПоПеречнюChanging(value);
					this.SendPropertyChanging();
					this._НомерПоПеречню = value;
					this.SendPropertyChanged("НомерПоПеречню");
					this.OnНомерПоПеречнюChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Сумма", DbType="Money")]
		public System.Nullable<decimal> Сумма
		{
			get
			{
				return this._Сумма;
			}
			set
			{
				if ((this._Сумма != value))
				{
					this.OnСуммаChanging(value);
					this.SendPropertyChanging();
					this._Сумма = value;
					this.SendPropertyChanged("Сумма");
					this.OnСуммаChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ТехЛист", DbType="Int")]
		public System.Nullable<int> ТехЛист
		{
			get
			{
				return this._ТехЛист;
			}
			set
			{
				if ((this._ТехЛист != value))
				{
					this.OnТехЛистChanging(value);
					this.SendPropertyChanging();
					this._ТехЛист = value;
					this.SendPropertyChanged("ТехЛист");
					this.OnТехЛистChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
