#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDantist
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Dentists")]
	public partial class DataClasses4DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    partial void InsertЛьготнаяКатегория(ЛьготнаяКатегория instance);
    partial void UpdateЛьготнаяКатегория(ЛьготнаяКатегория instance);
    partial void DeleteЛьготнаяКатегория(ЛьготнаяКатегория instance);
    #endregion
		
		public DataClasses4DataContext() : 
				base(global::ControlDantist.Properties.Settings.Default.DentistsConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses4DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses4DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses4DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses4DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ПоликлинникиИнн> ПоликлинникиИнн
		{
			get
			{
				return this.GetTable<ПоликлинникиИнн>();
			}
		}
		
		public System.Data.Linq.Table<ЛьготнаяКатегория> ЛьготнаяКатегория
		{
			get
			{
				return this.GetTable<ЛьготнаяКатегория>();
			}
		}
		
		public System.Data.Linq.Table<ViewСуммаДоговоровБезАкта> ViewСуммаДоговоровБезАкта
		{
			get
			{
				return this.GetTable<ViewСуммаДоговоровБезАкта>();
			}
		}
		
		public System.Data.Linq.Table<ViewИнвентаризация> ViewИнвентаризация
		{
			get
			{
				return this.GetTable<ViewИнвентаризация>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ПоликлинникиИнн")]
	public partial class ПоликлинникиИнн
	{
		
		private System.Nullable<double> _F1;
		
		private string _F2;
		
		private System.Nullable<double> _F3;
		
		public ПоликлинникиИнн()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F1", DbType="Float")]
		public System.Nullable<double> F1
		{
			get
			{
				return this._F1;
			}
			set
			{
				if ((this._F1 != value))
				{
					this._F1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F2", DbType="NVarChar(255)")]
		public string F2
		{
			get
			{
				return this._F2;
			}
			set
			{
				if ((this._F2 != value))
				{
					this._F2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F3", DbType="Float")]
		public System.Nullable<double> F3
		{
			get
			{
				return this._F3;
			}
			set
			{
				if ((this._F3 != value))
				{
					this._F3 = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ЛьготнаяКатегория")]
	public partial class ЛьготнаяКатегория : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_льготнойКатегории;
		
		private string _ЛьготнаяКатегория1;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_льготнойКатегорииChanging(int value);
    partial void Onid_льготнойКатегорииChanged();
    partial void OnЛьготнаяКатегория1Changing(string value);
    partial void OnЛьготнаяКатегория1Changed();
    #endregion
		
		public ЛьготнаяКатегория()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_льготнойКатегории", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_льготнойКатегории
		{
			get
			{
				return this._id_льготнойКатегории;
			}
			set
			{
				if ((this._id_льготнойКатегории != value))
				{
					this.Onid_льготнойКатегорииChanging(value);
					this.SendPropertyChanging();
					this._id_льготнойКатегории = value;
					this.SendPropertyChanged("id_льготнойКатегории");
					this.Onid_льготнойКатегорииChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ЛьготнаяКатегория", Storage="_ЛьготнаяКатегория1", DbType="NChar(200)")]
		public string ЛьготнаяКатегория1
		{
			get
			{
				return this._ЛьготнаяКатегория1;
			}
			set
			{
				if ((this._ЛьготнаяКатегория1 != value))
				{
					this.OnЛьготнаяКатегория1Changing(value);
					this.SendPropertyChanging();
					this._ЛьготнаяКатегория1 = value;
					this.SendPropertyChanged("ЛьготнаяКатегория1");
					this.OnЛьготнаяКатегория1Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ViewСуммаДоговоровБезАкта")]
	public partial class ViewСуммаДоговоровБезАкта
	{
		
		private string _Поликлинника;
		
		private System.Nullable<decimal> _Всего;
		
		private System.Nullable<decimal> _ВсегоВетеранТруда;
		
		private System.Nullable<decimal> _ВсегоВетеранВоеннойСлужбы;
		
		private System.Nullable<decimal> _ВсегоВетеранТрудаСаратовскойОбласти;
		
		private System.Nullable<decimal> _ВсегоТруженникТыла;
		
		private System.Nullable<decimal> _ВсегоРеабелитированные;
		
		public ViewСуммаДоговоровБезАкта()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Поликлинника", DbType="NVarChar(255)")]
		public string Поликлинника
		{
			get
			{
				return this._Поликлинника;
			}
			set
			{
				if ((this._Поликлинника != value))
				{
					this._Поликлинника = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Всего", DbType="Money")]
		public System.Nullable<decimal> Всего
		{
			get
			{
				return this._Всего;
			}
			set
			{
				if ((this._Всего != value))
				{
					this._Всего = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ВсегоВетеранТруда", DbType="Money")]
		public System.Nullable<decimal> ВсегоВетеранТруда
		{
			get
			{
				return this._ВсегоВетеранТруда;
			}
			set
			{
				if ((this._ВсегоВетеранТруда != value))
				{
					this._ВсегоВетеранТруда = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ВсегоВетеранВоеннойСлужбы", DbType="Money")]
		public System.Nullable<decimal> ВсегоВетеранВоеннойСлужбы
		{
			get
			{
				return this._ВсегоВетеранВоеннойСлужбы;
			}
			set
			{
				if ((this._ВсегоВетеранВоеннойСлужбы != value))
				{
					this._ВсегоВетеранВоеннойСлужбы = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ВсегоВетеранТрудаСаратовскойОбласти", DbType="Money")]
		public System.Nullable<decimal> ВсегоВетеранТрудаСаратовскойОбласти
		{
			get
			{
				return this._ВсегоВетеранТрудаСаратовскойОбласти;
			}
			set
			{
				if ((this._ВсегоВетеранТрудаСаратовскойОбласти != value))
				{
					this._ВсегоВетеранТрудаСаратовскойОбласти = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ВсегоТруженникТыла", DbType="Money")]
		public System.Nullable<decimal> ВсегоТруженникТыла
		{
			get
			{
				return this._ВсегоТруженникТыла;
			}
			set
			{
				if ((this._ВсегоТруженникТыла != value))
				{
					this._ВсегоТруженникТыла = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ВсегоРеабелитированные", DbType="Money")]
		public System.Nullable<decimal> ВсегоРеабелитированные
		{
			get
			{
				return this._ВсегоРеабелитированные;
			}
			set
			{
				if ((this._ВсегоРеабелитированные != value))
				{
					this._ВсегоРеабелитированные = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ViewИнвентаризация")]
	public partial class ViewИнвентаризация
	{
		
		private string _Фамилия;
		
		private string _Имя;
		
		private string _Отчество;
		
		private string _ЛьготнаяКатегория;
		
		private string _НомерДоговора;
		
		private System.Nullable<System.DateTime> _ДатаДоговора;
		
		private System.Nullable<System.DateTime> _ДатаАктаВыполненныхРабот;
		
		private string _НаименованиеПоликлинники;
		
		private System.Nullable<decimal> _СуммаАктаВыполненныхРабот;
		
		private string _logWrite;
		
		private System.Nullable<System.DateTime> _ДатаЗаписиДоговора;
		
		private string _ИНН;
		
		private string _F2;
		
		private System.Nullable<double> _F3;
		
		private string _НомерАкта;
		
		private System.Nullable<decimal> _СуммаДоговора;
		
		private System.Nullable<bool> _ФлагНаличияАкта;
		
		public ViewИнвентаризация()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Фамилия", DbType="NVarChar(150)")]
		public string Фамилия
		{
			get
			{
				return this._Фамилия;
			}
			set
			{
				if ((this._Фамилия != value))
				{
					this._Фамилия = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Имя", DbType="NVarChar(150)")]
		public string Имя
		{
			get
			{
				return this._Имя;
			}
			set
			{
				if ((this._Имя != value))
				{
					this._Имя = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Отчество", DbType="NVarChar(150)")]
		public string Отчество
		{
			get
			{
				return this._Отчество;
			}
			set
			{
				if ((this._Отчество != value))
				{
					this._Отчество = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ЛьготнаяКатегория", DbType="NChar(200)")]
		public string ЛьготнаяКатегория
		{
			get
			{
				return this._ЛьготнаяКатегория;
			}
			set
			{
				if ((this._ЛьготнаяКатегория != value))
				{
					this._ЛьготнаяКатегория = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_НомерДоговора", DbType="NChar(100)")]
		public string НомерДоговора
		{
			get
			{
				return this._НомерДоговора;
			}
			set
			{
				if ((this._НомерДоговора != value))
				{
					this._НомерДоговора = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ДатаДоговора", DbType="DateTime")]
		public System.Nullable<System.DateTime> ДатаДоговора
		{
			get
			{
				return this._ДатаДоговора;
			}
			set
			{
				if ((this._ДатаДоговора != value))
				{
					this._ДатаДоговора = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ДатаАктаВыполненныхРабот", DbType="DateTime")]
		public System.Nullable<System.DateTime> ДатаАктаВыполненныхРабот
		{
			get
			{
				return this._ДатаАктаВыполненныхРабот;
			}
			set
			{
				if ((this._ДатаАктаВыполненныхРабот != value))
				{
					this._ДатаАктаВыполненныхРабот = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_НаименованиеПоликлинники", DbType="NVarChar(300)")]
		public string НаименованиеПоликлинники
		{
			get
			{
				return this._НаименованиеПоликлинники;
			}
			set
			{
				if ((this._НаименованиеПоликлинники != value))
				{
					this._НаименованиеПоликлинники = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_СуммаАктаВыполненныхРабот", DbType="Money")]
		public System.Nullable<decimal> СуммаАктаВыполненныхРабот
		{
			get
			{
				return this._СуммаАктаВыполненныхРабот;
			}
			set
			{
				if ((this._СуммаАктаВыполненныхРабот != value))
				{
					this._СуммаАктаВыполненныхРабот = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logWrite", DbType="VarChar(150)")]
		public string logWrite
		{
			get
			{
				return this._logWrite;
			}
			set
			{
				if ((this._logWrite != value))
				{
					this._logWrite = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ДатаЗаписиДоговора", DbType="Date")]
		public System.Nullable<System.DateTime> ДатаЗаписиДоговора
		{
			get
			{
				return this._ДатаЗаписиДоговора;
			}
			set
			{
				if ((this._ДатаЗаписиДоговора != value))
				{
					this._ДатаЗаписиДоговора = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ИНН", DbType="NChar(20)")]
		public string ИНН
		{
			get
			{
				return this._ИНН;
			}
			set
			{
				if ((this._ИНН != value))
				{
					this._ИНН = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F2", DbType="NVarChar(255)")]
		public string F2
		{
			get
			{
				return this._F2;
			}
			set
			{
				if ((this._F2 != value))
				{
					this._F2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F3", DbType="Float")]
		public System.Nullable<double> F3
		{
			get
			{
				return this._F3;
			}
			set
			{
				if ((this._F3 != value))
				{
					this._F3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_НомерАкта", DbType="NChar(100)")]
		public string НомерАкта
		{
			get
			{
				return this._НомерАкта;
			}
			set
			{
				if ((this._НомерАкта != value))
				{
					this._НомерАкта = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_СуммаДоговора", DbType="Money")]
		public System.Nullable<decimal> СуммаДоговора
		{
			get
			{
				return this._СуммаДоговора;
			}
			set
			{
				if ((this._СуммаДоговора != value))
				{
					this._СуммаДоговора = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ФлагНаличияАкта", DbType="Bit")]
		public System.Nullable<bool> ФлагНаличияАкта
		{
			get
			{
				return this._ФлагНаличияАкта;
			}
			set
			{
				if ((this._ФлагНаличияАкта != value))
				{
					this._ФлагНаличияАкта = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
