#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDantist.Repozirories
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Dentists")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    partial void InsertРайонОбласти(РайонОбласти instance);
    partial void UpdateРайонОбласти(РайонОбласти instance);
    partial void DeleteРайонОбласти(РайонОбласти instance);
    partial void InsertNameOrganizationVipNet(NameOrganizationVipNet instance);
    partial void UpdateNameOrganizationVipNet(NameOrganizationVipNet instance);
    partial void DeleteNameOrganizationVipNet(NameOrganizationVipNet instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::ControlDantist.Properties.Settings.Default.DentistsConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<РайонОбласти> РайонОбласти
		{
			get
			{
				return this.GetTable<РайонОбласти>();
			}
		}
		
		public System.Data.Linq.Table<ViewPersonVipNet> ViewPersonVipNet
		{
			get
			{
				return this.GetTable<ViewPersonVipNet>();
			}
		}
		
		public System.Data.Linq.Table<NameOrganizationVipNet> NameOrganizationVipNet
		{
			get
			{
				return this.GetTable<NameOrganizationVipNet>();
			}
		}
		
		public System.Data.Linq.Table<ViewPersonVipNet2> ViewPersonVipNet2
		{
			get
			{
				return this.GetTable<ViewPersonVipNet2>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.РайонОбласти")]
	public partial class РайонОбласти : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idRegion;
		
		private string _NameRegion;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidRegionChanging(int value);
    partial void OnidRegionChanged();
    partial void OnNameRegionChanging(string value);
    partial void OnNameRegionChanged();
    #endregion
		
		public РайонОбласти()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRegion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idRegion
		{
			get
			{
				return this._idRegion;
			}
			set
			{
				if ((this._idRegion != value))
				{
					this.OnidRegionChanging(value);
					this.SendPropertyChanging();
					this._idRegion = value;
					this.SendPropertyChanged("idRegion");
					this.OnidRegionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameRegion", DbType="NVarChar(80)")]
		public string NameRegion
		{
			get
			{
				return this._NameRegion;
			}
			set
			{
				if ((this._NameRegion != value))
				{
					this.OnNameRegionChanging(value);
					this.SendPropertyChanging();
					this._NameRegion = value;
					this.SendPropertyChanged("NameRegion");
					this.OnNameRegionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ViewPersonVipNet")]
	public partial class ViewPersonVipNet
	{
		
		private string _NameRegion;
		
		private string _Наименование;
		
		private string _Фамилия;
		
		private string _Имя;
		
		private string _Отчество;
		
		private System.Nullable<System.DateTime> _ДатаРождения;
		
		private string _улица;
		
		private string _НомерДома;
		
		private string _корпус;
		
		private string _НомерКвартиры;
		
		private string _СерияДокумента;
		
		private string _НомерДокумента;
		
		private string _НомерАкта;
		
		private System.Nullable<System.DateTime> _ДатаПодписания;
		
		private System.Nullable<System.DateTime> _ДатаЗаписиДоговора;
		
		private bool _flagАнулирован;
		
		private int _idRegion;
		
		private System.Nullable<decimal> _СуммаАктаВыполненныхРабот;
		
		public ViewPersonVipNet()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameRegion", DbType="NVarChar(80)")]
		public string NameRegion
		{
			get
			{
				return this._NameRegion;
			}
			set
			{
				if ((this._NameRegion != value))
				{
					this._NameRegion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Наименование", DbType="NChar(250)")]
		public string Наименование
		{
			get
			{
				return this._Наименование;
			}
			set
			{
				if ((this._Наименование != value))
				{
					this._Наименование = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Фамилия", DbType="NVarChar(150)")]
		public string Фамилия
		{
			get
			{
				return this._Фамилия;
			}
			set
			{
				if ((this._Фамилия != value))
				{
					this._Фамилия = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Имя", DbType="NVarChar(150)")]
		public string Имя
		{
			get
			{
				return this._Имя;
			}
			set
			{
				if ((this._Имя != value))
				{
					this._Имя = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Отчество", DbType="NVarChar(150)")]
		public string Отчество
		{
			get
			{
				return this._Отчество;
			}
			set
			{
				if ((this._Отчество != value))
				{
					this._Отчество = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ДатаРождения", DbType="Date")]
		public System.Nullable<System.DateTime> ДатаРождения
		{
			get
			{
				return this._ДатаРождения;
			}
			set
			{
				if ((this._ДатаРождения != value))
				{
					this._ДатаРождения = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_улица", DbType="NVarChar(200)")]
		public string улица
		{
			get
			{
				return this._улица;
			}
			set
			{
				if ((this._улица != value))
				{
					this._улица = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_НомерДома", DbType="NChar(10)")]
		public string НомерДома
		{
			get
			{
				return this._НомерДома;
			}
			set
			{
				if ((this._НомерДома != value))
				{
					this._НомерДома = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_корпус", DbType="NChar(10)")]
		public string корпус
		{
			get
			{
				return this._корпус;
			}
			set
			{
				if ((this._корпус != value))
				{
					this._корпус = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_НомерКвартиры", DbType="NChar(40)")]
		public string НомерКвартиры
		{
			get
			{
				return this._НомерКвартиры;
			}
			set
			{
				if ((this._НомерКвартиры != value))
				{
					this._НомерКвартиры = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_СерияДокумента", DbType="NChar(50)")]
		public string СерияДокумента
		{
			get
			{
				return this._СерияДокумента;
			}
			set
			{
				if ((this._СерияДокумента != value))
				{
					this._СерияДокумента = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_НомерДокумента", DbType="NChar(50)")]
		public string НомерДокумента
		{
			get
			{
				return this._НомерДокумента;
			}
			set
			{
				if ((this._НомерДокумента != value))
				{
					this._НомерДокумента = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_НомерАкта", DbType="NChar(100)")]
		public string НомерАкта
		{
			get
			{
				return this._НомерАкта;
			}
			set
			{
				if ((this._НомерАкта != value))
				{
					this._НомерАкта = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ДатаПодписания", DbType="DateTime")]
		public System.Nullable<System.DateTime> ДатаПодписания
		{
			get
			{
				return this._ДатаПодписания;
			}
			set
			{
				if ((this._ДатаПодписания != value))
				{
					this._ДатаПодписания = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ДатаЗаписиДоговора", DbType="Date")]
		public System.Nullable<System.DateTime> ДатаЗаписиДоговора
		{
			get
			{
				return this._ДатаЗаписиДоговора;
			}
			set
			{
				if ((this._ДатаЗаписиДоговора != value))
				{
					this._ДатаЗаписиДоговора = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flagАнулирован", DbType="Bit NOT NULL")]
		public bool flagАнулирован
		{
			get
			{
				return this._flagАнулирован;
			}
			set
			{
				if ((this._flagАнулирован != value))
				{
					this._flagАнулирован = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRegion", DbType="Int NOT NULL")]
		public int idRegion
		{
			get
			{
				return this._idRegion;
			}
			set
			{
				if ((this._idRegion != value))
				{
					this._idRegion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_СуммаАктаВыполненныхРабот", DbType="Money")]
		public System.Nullable<decimal> СуммаАктаВыполненныхРабот
		{
			get
			{
				return this._СуммаАктаВыполненныхРабот;
			}
			set
			{
				if ((this._СуммаАктаВыполненныхРабот != value))
				{
					this._СуммаАктаВыполненныхРабот = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NameOrganizationVipNet")]
	public partial class NameOrganizationVipNet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _NameOrganization;
		
		private string _Chief;
		
		private System.Nullable<int> _idRegion;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnNameOrganizationChanging(string value);
    partial void OnNameOrganizationChanged();
    partial void OnChiefChanging(string value);
    partial void OnChiefChanged();
    partial void OnidRegionChanging(System.Nullable<int> value);
    partial void OnidRegionChanged();
    #endregion
		
		public NameOrganizationVipNet()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameOrganization", DbType="NVarChar(200)")]
		public string NameOrganization
		{
			get
			{
				return this._NameOrganization;
			}
			set
			{
				if ((this._NameOrganization != value))
				{
					this.OnNameOrganizationChanging(value);
					this.SendPropertyChanging();
					this._NameOrganization = value;
					this.SendPropertyChanged("NameOrganization");
					this.OnNameOrganizationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chief", DbType="NVarChar(50)")]
		public string Chief
		{
			get
			{
				return this._Chief;
			}
			set
			{
				if ((this._Chief != value))
				{
					this.OnChiefChanging(value);
					this.SendPropertyChanging();
					this._Chief = value;
					this.SendPropertyChanged("Chief");
					this.OnChiefChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRegion", DbType="Int")]
		public System.Nullable<int> idRegion
		{
			get
			{
				return this._idRegion;
			}
			set
			{
				if ((this._idRegion != value))
				{
					this.OnidRegionChanging(value);
					this.SendPropertyChanging();
					this._idRegion = value;
					this.SendPropertyChanged("idRegion");
					this.OnidRegionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ViewPersonVipNet2")]
	public partial class ViewPersonVipNet2
	{
		
		private string _Фамилия;
		
		private string _Имя;
		
		private string _Отчество;
		
		private System.Nullable<System.DateTime> _ДатаРождения;
		
		private string _Улица;
		
		private string _НомерДома;
		
		private string _Корпус;
		
		private string _НомерКвартиры;
		
		private System.Nullable<int> _id_район;
		
		private System.Nullable<int> _id_насПункт;
		
		private string _NameRegion;
		
		private string _Наименование;
		
		private string _НомерАкта;
		
		private string _ДатаАкта;
		
		private string _СерияДокумента;
		
		private string _НомерДокумента;
		
		private System.Nullable<decimal> _СуммаАктаВыполненныхРабот;
		
		private System.Nullable<System.DateTime> _ДатаПодписания;
		
		public ViewPersonVipNet2()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Фамилия", DbType="NVarChar(150)")]
		public string Фамилия
		{
			get
			{
				return this._Фамилия;
			}
			set
			{
				if ((this._Фамилия != value))
				{
					this._Фамилия = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Имя", DbType="NVarChar(150)")]
		public string Имя
		{
			get
			{
				return this._Имя;
			}
			set
			{
				if ((this._Имя != value))
				{
					this._Имя = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Отчество", DbType="NVarChar(150)")]
		public string Отчество
		{
			get
			{
				return this._Отчество;
			}
			set
			{
				if ((this._Отчество != value))
				{
					this._Отчество = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ДатаРождения", DbType="Date")]
		public System.Nullable<System.DateTime> ДатаРождения
		{
			get
			{
				return this._ДатаРождения;
			}
			set
			{
				if ((this._ДатаРождения != value))
				{
					this._ДатаРождения = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Улица", DbType="NVarChar(200)")]
		public string Улица
		{
			get
			{
				return this._Улица;
			}
			set
			{
				if ((this._Улица != value))
				{
					this._Улица = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_НомерДома", DbType="NChar(10)")]
		public string НомерДома
		{
			get
			{
				return this._НомерДома;
			}
			set
			{
				if ((this._НомерДома != value))
				{
					this._НомерДома = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Корпус", DbType="NChar(10)")]
		public string Корпус
		{
			get
			{
				return this._Корпус;
			}
			set
			{
				if ((this._Корпус != value))
				{
					this._Корпус = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_НомерКвартиры", DbType="NChar(40)")]
		public string НомерКвартиры
		{
			get
			{
				return this._НомерКвартиры;
			}
			set
			{
				if ((this._НомерКвартиры != value))
				{
					this._НомерКвартиры = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_район", DbType="Int")]
		public System.Nullable<int> id_район
		{
			get
			{
				return this._id_район;
			}
			set
			{
				if ((this._id_район != value))
				{
					this._id_район = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_насПункт", DbType="Int")]
		public System.Nullable<int> id_насПункт
		{
			get
			{
				return this._id_насПункт;
			}
			set
			{
				if ((this._id_насПункт != value))
				{
					this._id_насПункт = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameRegion", DbType="NVarChar(80)")]
		public string NameRegion
		{
			get
			{
				return this._NameRegion;
			}
			set
			{
				if ((this._NameRegion != value))
				{
					this._NameRegion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Наименование", DbType="NChar(250)")]
		public string Наименование
		{
			get
			{
				return this._Наименование;
			}
			set
			{
				if ((this._Наименование != value))
				{
					this._Наименование = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_НомерАкта", DbType="NChar(100)")]
		public string НомерАкта
		{
			get
			{
				return this._НомерАкта;
			}
			set
			{
				if ((this._НомерАкта != value))
				{
					this._НомерАкта = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ДатаАкта", DbType="VarChar(8)")]
		public string ДатаАкта
		{
			get
			{
				return this._ДатаАкта;
			}
			set
			{
				if ((this._ДатаАкта != value))
				{
					this._ДатаАкта = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_СерияДокумента", DbType="NChar(50)")]
		public string СерияДокумента
		{
			get
			{
				return this._СерияДокумента;
			}
			set
			{
				if ((this._СерияДокумента != value))
				{
					this._СерияДокумента = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_НомерДокумента", DbType="NChar(50)")]
		public string НомерДокумента
		{
			get
			{
				return this._НомерДокумента;
			}
			set
			{
				if ((this._НомерДокумента != value))
				{
					this._НомерДокумента = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_СуммаАктаВыполненныхРабот", DbType="Money")]
		public System.Nullable<decimal> СуммаАктаВыполненныхРабот
		{
			get
			{
				return this._СуммаАктаВыполненныхРабот;
			}
			set
			{
				if ((this._СуммаАктаВыполненныхРабот != value))
				{
					this._СуммаАктаВыполненныхРабот = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ДатаПодписания", DbType="DateTime")]
		public System.Nullable<System.DateTime> ДатаПодписания
		{
			get
			{
				return this._ДатаПодписания;
			}
			set
			{
				if ((this._ДатаПодписания != value))
				{
					this._ДатаПодписания = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
