#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.1
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Dentists")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    partial void InsertДоговор(Договор instance);
    partial void UpdateДоговор(Договор instance);
    partial void DeleteДоговор(Договор instance);
    partial void InsertАктВыполненныхРабот(АктВыполненныхРабот instance);
    partial void UpdateАктВыполненныхРабот(АктВыполненныхРабот instance);
    partial void DeleteАктВыполненныхРабот(АктВыполненныхРабот instance);
    partial void InsertЛьготник(Льготник instance);
    partial void UpdateЛьготник(Льготник instance);
    partial void DeleteЛьготник(Льготник instance);
    partial void InsertУслугиПоДоговору(УслугиПоДоговору instance);
    partial void UpdateУслугиПоДоговору(УслугиПоДоговору instance);
    partial void DeleteУслугиПоДоговору(УслугиПоДоговору instance);
    partial void InsertПоликлинника(Поликлинника instance);
    partial void UpdateПоликлинника(Поликлинника instance);
    partial void DeleteПоликлинника(Поликлинника instance);
    partial void InsertЛьготнаяКатегория(ЛьготнаяКатегория instance);
    partial void UpdateЛьготнаяКатегория(ЛьготнаяКатегория instance);
    partial void DeleteЛьготнаяКатегория(ЛьготнаяКатегория instance);
    partial void InsertТипДокумента(ТипДокумента instance);
    partial void UpdateТипДокумента(ТипДокумента instance);
    partial void DeleteТипДокумента(ТипДокумента instance);
    partial void InsertНаселённыйПункт(НаселённыйПункт instance);
    partial void UpdateНаселённыйПункт(НаселённыйПункт instance);
    partial void DeleteНаселённыйПункт(НаселённыйПункт instance);
    partial void InsertНаименованиеРайона(НаименованиеРайона instance);
    partial void UpdateНаименованиеРайона(НаименованиеРайона instance);
    partial void DeleteНаименованиеРайона(НаименованиеРайона instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::ClassLibrary1.Properties.Settings.Default.DentistsConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Договор> Договор
		{
			get
			{
				return this.GetTable<Договор>();
			}
		}
		
		public System.Data.Linq.Table<АктВыполненныхРабот> АктВыполненныхРабот
		{
			get
			{
				return this.GetTable<АктВыполненныхРабот>();
			}
		}
		
		public System.Data.Linq.Table<Льготник> Льготник
		{
			get
			{
				return this.GetTable<Льготник>();
			}
		}
		
		public System.Data.Linq.Table<УслугиПоДоговору> УслугиПоДоговору
		{
			get
			{
				return this.GetTable<УслугиПоДоговору>();
			}
		}
		
		public System.Data.Linq.Table<Поликлинника> Поликлинника
		{
			get
			{
				return this.GetTable<Поликлинника>();
			}
		}
		
		public System.Data.Linq.Table<ЛьготнаяКатегория> ЛьготнаяКатегория
		{
			get
			{
				return this.GetTable<ЛьготнаяКатегория>();
			}
		}
		
		public System.Data.Linq.Table<ТипДокумента> ТипДокумента
		{
			get
			{
				return this.GetTable<ТипДокумента>();
			}
		}
		
		public System.Data.Linq.Table<НаселённыйПункт> НаселённыйПункт
		{
			get
			{
				return this.GetTable<НаселённыйПункт>();
			}
		}
		
		public System.Data.Linq.Table<НаименованиеРайона> НаименованиеРайона
		{
			get
			{
				return this.GetTable<НаименованиеРайона>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Договор")]
	public partial class Договор : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_договор;
		
		private string _НомерДоговора;
		
		private System.Nullable<System.DateTime> _ДатаДоговора;
		
		private System.Nullable<System.DateTime> _ДатаАктаВыполненныхРабот;
		
		private System.Nullable<decimal> _СуммаАктаВыполненныхРабот;
		
		private System.Nullable<int> _id_льготнаяКатегория;
		
		private System.Nullable<int> _id_поликлинника;
		
		private string _Примечание;
		
		private System.Nullable<int> _id_комитет;
		
		private System.Nullable<bool> _ФлагНаличияДоговора;
		
		private System.Nullable<bool> _ФлагНаличияАкта;
		
		private System.Nullable<int> _id_льготник;
		
		private string _ФлагДопСоглашения;
		
		private System.Nullable<bool> _флагСРН;
		
		private System.Nullable<bool> _флагУслуги;
		
		private System.Nullable<System.DateTime> _датаВозврата;
		
		private System.Nullable<System.DateTime> _ДатаЗаписиДоговора;
		
		private System.Nullable<bool> _ФлагПроверки;
		
		private string _НомерРеестра;
		
		private System.Nullable<System.DateTime> _ДатаРеестра;
		
		private string _НомерСчётФактрура;
		
		private System.Nullable<System.DateTime> _ДатаСчётФактура;
		
		private string _logWrite;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_договорChanging(int value);
    partial void Onid_договорChanged();
    partial void OnНомерДоговораChanging(string value);
    partial void OnНомерДоговораChanged();
    partial void OnДатаДоговораChanging(System.Nullable<System.DateTime> value);
    partial void OnДатаДоговораChanged();
    partial void OnДатаАктаВыполненныхРаботChanging(System.Nullable<System.DateTime> value);
    partial void OnДатаАктаВыполненныхРаботChanged();
    partial void OnСуммаАктаВыполненныхРаботChanging(System.Nullable<decimal> value);
    partial void OnСуммаАктаВыполненныхРаботChanged();
    partial void Onid_льготнаяКатегорияChanging(System.Nullable<int> value);
    partial void Onid_льготнаяКатегорияChanged();
    partial void Onid_поликлинникаChanging(System.Nullable<int> value);
    partial void Onid_поликлинникаChanged();
    partial void OnПримечаниеChanging(string value);
    partial void OnПримечаниеChanged();
    partial void Onid_комитетChanging(System.Nullable<int> value);
    partial void Onid_комитетChanged();
    partial void OnФлагНаличияДоговораChanging(System.Nullable<bool> value);
    partial void OnФлагНаличияДоговораChanged();
    partial void OnФлагНаличияАктаChanging(System.Nullable<bool> value);
    partial void OnФлагНаличияАктаChanged();
    partial void Onid_льготникChanging(System.Nullable<int> value);
    partial void Onid_льготникChanged();
    partial void OnФлагДопСоглашенияChanging(string value);
    partial void OnФлагДопСоглашенияChanged();
    partial void OnфлагСРНChanging(System.Nullable<bool> value);
    partial void OnфлагСРНChanged();
    partial void OnфлагУслугиChanging(System.Nullable<bool> value);
    partial void OnфлагУслугиChanged();
    partial void OnдатаВозвратаChanging(System.Nullable<System.DateTime> value);
    partial void OnдатаВозвратаChanged();
    partial void OnДатаЗаписиДоговораChanging(System.Nullable<System.DateTime> value);
    partial void OnДатаЗаписиДоговораChanged();
    partial void OnФлагПроверкиChanging(System.Nullable<bool> value);
    partial void OnФлагПроверкиChanged();
    partial void OnНомерРеестраChanging(string value);
    partial void OnНомерРеестраChanged();
    partial void OnДатаРеестраChanging(System.Nullable<System.DateTime> value);
    partial void OnДатаРеестраChanged();
    partial void OnНомерСчётФактрураChanging(string value);
    partial void OnНомерСчётФактрураChanged();
    partial void OnДатаСчётФактураChanging(System.Nullable<System.DateTime> value);
    partial void OnДатаСчётФактураChanged();
    partial void OnlogWriteChanging(string value);
    partial void OnlogWriteChanged();
    #endregion
		
		public Договор()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_договор", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_договор
		{
			get
			{
				return this._id_договор;
			}
			set
			{
				if ((this._id_договор != value))
				{
					this.Onid_договорChanging(value);
					this.SendPropertyChanging();
					this._id_договор = value;
					this.SendPropertyChanged("id_договор");
					this.Onid_договорChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_НомерДоговора", DbType="NChar(100)")]
		public string НомерДоговора
		{
			get
			{
				return this._НомерДоговора;
			}
			set
			{
				if ((this._НомерДоговора != value))
				{
					this.OnНомерДоговораChanging(value);
					this.SendPropertyChanging();
					this._НомерДоговора = value;
					this.SendPropertyChanged("НомерДоговора");
					this.OnНомерДоговораChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ДатаДоговора", DbType="DateTime")]
		public System.Nullable<System.DateTime> ДатаДоговора
		{
			get
			{
				return this._ДатаДоговора;
			}
			set
			{
				if ((this._ДатаДоговора != value))
				{
					this.OnДатаДоговораChanging(value);
					this.SendPropertyChanging();
					this._ДатаДоговора = value;
					this.SendPropertyChanged("ДатаДоговора");
					this.OnДатаДоговораChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ДатаАктаВыполненныхРабот", DbType="DateTime")]
		public System.Nullable<System.DateTime> ДатаАктаВыполненныхРабот
		{
			get
			{
				return this._ДатаАктаВыполненныхРабот;
			}
			set
			{
				if ((this._ДатаАктаВыполненныхРабот != value))
				{
					this.OnДатаАктаВыполненныхРаботChanging(value);
					this.SendPropertyChanging();
					this._ДатаАктаВыполненныхРабот = value;
					this.SendPropertyChanged("ДатаАктаВыполненныхРабот");
					this.OnДатаАктаВыполненныхРаботChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_СуммаАктаВыполненныхРабот", DbType="Money")]
		public System.Nullable<decimal> СуммаАктаВыполненныхРабот
		{
			get
			{
				return this._СуммаАктаВыполненныхРабот;
			}
			set
			{
				if ((this._СуммаАктаВыполненныхРабот != value))
				{
					this.OnСуммаАктаВыполненныхРаботChanging(value);
					this.SendPropertyChanging();
					this._СуммаАктаВыполненныхРабот = value;
					this.SendPropertyChanged("СуммаАктаВыполненныхРабот");
					this.OnСуммаАктаВыполненныхРаботChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_льготнаяКатегория", DbType="Int")]
		public System.Nullable<int> id_льготнаяКатегория
		{
			get
			{
				return this._id_льготнаяКатегория;
			}
			set
			{
				if ((this._id_льготнаяКатегория != value))
				{
					this.Onid_льготнаяКатегорияChanging(value);
					this.SendPropertyChanging();
					this._id_льготнаяКатегория = value;
					this.SendPropertyChanged("id_льготнаяКатегория");
					this.Onid_льготнаяКатегорияChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_поликлинника", DbType="Int")]
		public System.Nullable<int> id_поликлинника
		{
			get
			{
				return this._id_поликлинника;
			}
			set
			{
				if ((this._id_поликлинника != value))
				{
					this.Onid_поликлинникаChanging(value);
					this.SendPropertyChanging();
					this._id_поликлинника = value;
					this.SendPropertyChanged("id_поликлинника");
					this.Onid_поликлинникаChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Примечание", DbType="NVarChar(300)")]
		public string Примечание
		{
			get
			{
				return this._Примечание;
			}
			set
			{
				if ((this._Примечание != value))
				{
					this.OnПримечаниеChanging(value);
					this.SendPropertyChanging();
					this._Примечание = value;
					this.SendPropertyChanged("Примечание");
					this.OnПримечаниеChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_комитет", DbType="Int")]
		public System.Nullable<int> id_комитет
		{
			get
			{
				return this._id_комитет;
			}
			set
			{
				if ((this._id_комитет != value))
				{
					this.Onid_комитетChanging(value);
					this.SendPropertyChanging();
					this._id_комитет = value;
					this.SendPropertyChanged("id_комитет");
					this.Onid_комитетChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ФлагНаличияДоговора", DbType="Bit")]
		public System.Nullable<bool> ФлагНаличияДоговора
		{
			get
			{
				return this._ФлагНаличияДоговора;
			}
			set
			{
				if ((this._ФлагНаличияДоговора != value))
				{
					this.OnФлагНаличияДоговораChanging(value);
					this.SendPropertyChanging();
					this._ФлагНаличияДоговора = value;
					this.SendPropertyChanged("ФлагНаличияДоговора");
					this.OnФлагНаличияДоговораChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ФлагНаличияАкта", DbType="Bit")]
		public System.Nullable<bool> ФлагНаличияАкта
		{
			get
			{
				return this._ФлагНаличияАкта;
			}
			set
			{
				if ((this._ФлагНаличияАкта != value))
				{
					this.OnФлагНаличияАктаChanging(value);
					this.SendPropertyChanging();
					this._ФлагНаличияАкта = value;
					this.SendPropertyChanged("ФлагНаличияАкта");
					this.OnФлагНаличияАктаChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_льготник", DbType="Int")]
		public System.Nullable<int> id_льготник
		{
			get
			{
				return this._id_льготник;
			}
			set
			{
				if ((this._id_льготник != value))
				{
					this.Onid_льготникChanging(value);
					this.SendPropertyChanging();
					this._id_льготник = value;
					this.SendPropertyChanged("id_льготник");
					this.Onid_льготникChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ФлагДопСоглашения", DbType="NChar(50)")]
		public string ФлагДопСоглашения
		{
			get
			{
				return this._ФлагДопСоглашения;
			}
			set
			{
				if ((this._ФлагДопСоглашения != value))
				{
					this.OnФлагДопСоглашенияChanging(value);
					this.SendPropertyChanging();
					this._ФлагДопСоглашения = value;
					this.SendPropertyChanged("ФлагДопСоглашения");
					this.OnФлагДопСоглашенияChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_флагСРН", DbType="Bit")]
		public System.Nullable<bool> флагСРН
		{
			get
			{
				return this._флагСРН;
			}
			set
			{
				if ((this._флагСРН != value))
				{
					this.OnфлагСРНChanging(value);
					this.SendPropertyChanging();
					this._флагСРН = value;
					this.SendPropertyChanged("флагСРН");
					this.OnфлагСРНChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_флагУслуги", DbType="Bit")]
		public System.Nullable<bool> флагУслуги
		{
			get
			{
				return this._флагУслуги;
			}
			set
			{
				if ((this._флагУслуги != value))
				{
					this.OnфлагУслугиChanging(value);
					this.SendPropertyChanging();
					this._флагУслуги = value;
					this.SendPropertyChanged("флагУслуги");
					this.OnфлагУслугиChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_датаВозврата", DbType="DateTime")]
		public System.Nullable<System.DateTime> датаВозврата
		{
			get
			{
				return this._датаВозврата;
			}
			set
			{
				if ((this._датаВозврата != value))
				{
					this.OnдатаВозвратаChanging(value);
					this.SendPropertyChanging();
					this._датаВозврата = value;
					this.SendPropertyChanged("датаВозврата");
					this.OnдатаВозвратаChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ДатаЗаписиДоговора", DbType="Date")]
		public System.Nullable<System.DateTime> ДатаЗаписиДоговора
		{
			get
			{
				return this._ДатаЗаписиДоговора;
			}
			set
			{
				if ((this._ДатаЗаписиДоговора != value))
				{
					this.OnДатаЗаписиДоговораChanging(value);
					this.SendPropertyChanging();
					this._ДатаЗаписиДоговора = value;
					this.SendPropertyChanged("ДатаЗаписиДоговора");
					this.OnДатаЗаписиДоговораChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ФлагПроверки", DbType="Bit")]
		public System.Nullable<bool> ФлагПроверки
		{
			get
			{
				return this._ФлагПроверки;
			}
			set
			{
				if ((this._ФлагПроверки != value))
				{
					this.OnФлагПроверкиChanging(value);
					this.SendPropertyChanging();
					this._ФлагПроверки = value;
					this.SendPropertyChanged("ФлагПроверки");
					this.OnФлагПроверкиChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_НомерРеестра", DbType="NChar(30)")]
		public string НомерРеестра
		{
			get
			{
				return this._НомерРеестра;
			}
			set
			{
				if ((this._НомерРеестра != value))
				{
					this.OnНомерРеестраChanging(value);
					this.SendPropertyChanging();
					this._НомерРеестра = value;
					this.SendPropertyChanged("НомерРеестра");
					this.OnНомерРеестраChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ДатаРеестра", DbType="Date")]
		public System.Nullable<System.DateTime> ДатаРеестра
		{
			get
			{
				return this._ДатаРеестра;
			}
			set
			{
				if ((this._ДатаРеестра != value))
				{
					this.OnДатаРеестраChanging(value);
					this.SendPropertyChanging();
					this._ДатаРеестра = value;
					this.SendPropertyChanged("ДатаРеестра");
					this.OnДатаРеестраChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_НомерСчётФактрура", DbType="NChar(30)")]
		public string НомерСчётФактрура
		{
			get
			{
				return this._НомерСчётФактрура;
			}
			set
			{
				if ((this._НомерСчётФактрура != value))
				{
					this.OnНомерСчётФактрураChanging(value);
					this.SendPropertyChanging();
					this._НомерСчётФактрура = value;
					this.SendPropertyChanged("НомерСчётФактрура");
					this.OnНомерСчётФактрураChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ДатаСчётФактура", DbType="Date")]
		public System.Nullable<System.DateTime> ДатаСчётФактура
		{
			get
			{
				return this._ДатаСчётФактура;
			}
			set
			{
				if ((this._ДатаСчётФактура != value))
				{
					this.OnДатаСчётФактураChanging(value);
					this.SendPropertyChanging();
					this._ДатаСчётФактура = value;
					this.SendPropertyChanged("ДатаСчётФактура");
					this.OnДатаСчётФактураChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logWrite", DbType="VarChar(150)")]
		public string logWrite
		{
			get
			{
				return this._logWrite;
			}
			set
			{
				if ((this._logWrite != value))
				{
					this.OnlogWriteChanging(value);
					this.SendPropertyChanging();
					this._logWrite = value;
					this.SendPropertyChanged("logWrite");
					this.OnlogWriteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.АктВыполненныхРабот")]
	public partial class АктВыполненныхРабот : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_акт;
		
		private string _НомерАкта;
		
		private System.Nullable<int> _id_договор;
		
		private string _ФлагПодписания;
		
		private System.Nullable<System.DateTime> _ДатаПодписания;
		
		private string _НомерПоПеречню;
		
		private string _НаименованиеУслуги;
		
		private System.Nullable<decimal> _Цена;
		
		private System.Nullable<int> _Количество;
		
		private System.Nullable<decimal> _Сумма;
		
		private string _ФлагДопСоглашение;
		
		private string _НомерРеестра;
		
		private System.Nullable<System.DateTime> _ДатаРеестра;
		
		private string _НомерСчётФактуры;
		
		private System.Nullable<System.DateTime> _ДатаСчётФактуры;
		
		private string _ДатаОплаты;
		
		private string _logWrite;
		
		private string _logDate;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_актChanging(int value);
    partial void Onid_актChanged();
    partial void OnНомерАктаChanging(string value);
    partial void OnНомерАктаChanged();
    partial void Onid_договорChanging(System.Nullable<int> value);
    partial void Onid_договорChanged();
    partial void OnФлагПодписанияChanging(string value);
    partial void OnФлагПодписанияChanged();
    partial void OnДатаПодписанияChanging(System.Nullable<System.DateTime> value);
    partial void OnДатаПодписанияChanged();
    partial void OnНомерПоПеречнюChanging(string value);
    partial void OnНомерПоПеречнюChanged();
    partial void OnНаименованиеУслугиChanging(string value);
    partial void OnНаименованиеУслугиChanged();
    partial void OnЦенаChanging(System.Nullable<decimal> value);
    partial void OnЦенаChanged();
    partial void OnКоличествоChanging(System.Nullable<int> value);
    partial void OnКоличествоChanged();
    partial void OnСуммаChanging(System.Nullable<decimal> value);
    partial void OnСуммаChanged();
    partial void OnФлагДопСоглашениеChanging(string value);
    partial void OnФлагДопСоглашениеChanged();
    partial void OnНомерРеестраChanging(string value);
    partial void OnНомерРеестраChanged();
    partial void OnДатаРеестраChanging(System.Nullable<System.DateTime> value);
    partial void OnДатаРеестраChanged();
    partial void OnНомерСчётФактурыChanging(string value);
    partial void OnНомерСчётФактурыChanged();
    partial void OnДатаСчётФактурыChanging(System.Nullable<System.DateTime> value);
    partial void OnДатаСчётФактурыChanged();
    partial void OnДатаОплатыChanging(string value);
    partial void OnДатаОплатыChanged();
    partial void OnlogWriteChanging(string value);
    partial void OnlogWriteChanged();
    partial void OnlogDateChanging(string value);
    partial void OnlogDateChanged();
    #endregion
		
		public АктВыполненныхРабот()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_акт", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_акт
		{
			get
			{
				return this._id_акт;
			}
			set
			{
				if ((this._id_акт != value))
				{
					this.Onid_актChanging(value);
					this.SendPropertyChanging();
					this._id_акт = value;
					this.SendPropertyChanged("id_акт");
					this.Onid_актChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_НомерАкта", DbType="NChar(100)")]
		public string НомерАкта
		{
			get
			{
				return this._НомерАкта;
			}
			set
			{
				if ((this._НомерАкта != value))
				{
					this.OnНомерАктаChanging(value);
					this.SendPropertyChanging();
					this._НомерАкта = value;
					this.SendPropertyChanged("НомерАкта");
					this.OnНомерАктаChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_договор", DbType="Int")]
		public System.Nullable<int> id_договор
		{
			get
			{
				return this._id_договор;
			}
			set
			{
				if ((this._id_договор != value))
				{
					this.Onid_договорChanging(value);
					this.SendPropertyChanging();
					this._id_договор = value;
					this.SendPropertyChanged("id_договор");
					this.Onid_договорChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ФлагПодписания", DbType="NChar(10)")]
		public string ФлагПодписания
		{
			get
			{
				return this._ФлагПодписания;
			}
			set
			{
				if ((this._ФлагПодписания != value))
				{
					this.OnФлагПодписанияChanging(value);
					this.SendPropertyChanging();
					this._ФлагПодписания = value;
					this.SendPropertyChanged("ФлагПодписания");
					this.OnФлагПодписанияChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ДатаПодписания", DbType="DateTime")]
		public System.Nullable<System.DateTime> ДатаПодписания
		{
			get
			{
				return this._ДатаПодписания;
			}
			set
			{
				if ((this._ДатаПодписания != value))
				{
					this.OnДатаПодписанияChanging(value);
					this.SendPropertyChanging();
					this._ДатаПодписания = value;
					this.SendPropertyChanged("ДатаПодписания");
					this.OnДатаПодписанияChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_НомерПоПеречню", DbType="NChar(50)")]
		public string НомерПоПеречню
		{
			get
			{
				return this._НомерПоПеречню;
			}
			set
			{
				if ((this._НомерПоПеречню != value))
				{
					this.OnНомерПоПеречнюChanging(value);
					this.SendPropertyChanging();
					this._НомерПоПеречню = value;
					this.SendPropertyChanged("НомерПоПеречню");
					this.OnНомерПоПеречнюChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_НаименованиеУслуги", DbType="NVarChar(300)")]
		public string НаименованиеУслуги
		{
			get
			{
				return this._НаименованиеУслуги;
			}
			set
			{
				if ((this._НаименованиеУслуги != value))
				{
					this.OnНаименованиеУслугиChanging(value);
					this.SendPropertyChanging();
					this._НаименованиеУслуги = value;
					this.SendPropertyChanged("НаименованиеУслуги");
					this.OnНаименованиеУслугиChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Цена", DbType="Money")]
		public System.Nullable<decimal> Цена
		{
			get
			{
				return this._Цена;
			}
			set
			{
				if ((this._Цена != value))
				{
					this.OnЦенаChanging(value);
					this.SendPropertyChanging();
					this._Цена = value;
					this.SendPropertyChanged("Цена");
					this.OnЦенаChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Количество", DbType="Int")]
		public System.Nullable<int> Количество
		{
			get
			{
				return this._Количество;
			}
			set
			{
				if ((this._Количество != value))
				{
					this.OnКоличествоChanging(value);
					this.SendPropertyChanging();
					this._Количество = value;
					this.SendPropertyChanged("Количество");
					this.OnКоличествоChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Сумма", DbType="Money")]
		public System.Nullable<decimal> Сумма
		{
			get
			{
				return this._Сумма;
			}
			set
			{
				if ((this._Сумма != value))
				{
					this.OnСуммаChanging(value);
					this.SendPropertyChanging();
					this._Сумма = value;
					this.SendPropertyChanged("Сумма");
					this.OnСуммаChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ФлагДопСоглашение", DbType="NChar(5)")]
		public string ФлагДопСоглашение
		{
			get
			{
				return this._ФлагДопСоглашение;
			}
			set
			{
				if ((this._ФлагДопСоглашение != value))
				{
					this.OnФлагДопСоглашениеChanging(value);
					this.SendPropertyChanging();
					this._ФлагДопСоглашение = value;
					this.SendPropertyChanged("ФлагДопСоглашение");
					this.OnФлагДопСоглашениеChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_НомерРеестра", DbType="NChar(10)")]
		public string НомерРеестра
		{
			get
			{
				return this._НомерРеестра;
			}
			set
			{
				if ((this._НомерРеестра != value))
				{
					this.OnНомерРеестраChanging(value);
					this.SendPropertyChanging();
					this._НомерРеестра = value;
					this.SendPropertyChanged("НомерРеестра");
					this.OnНомерРеестраChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ДатаРеестра", DbType="Date")]
		public System.Nullable<System.DateTime> ДатаРеестра
		{
			get
			{
				return this._ДатаРеестра;
			}
			set
			{
				if ((this._ДатаРеестра != value))
				{
					this.OnДатаРеестраChanging(value);
					this.SendPropertyChanging();
					this._ДатаРеестра = value;
					this.SendPropertyChanged("ДатаРеестра");
					this.OnДатаРеестраChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_НомерСчётФактуры", DbType="NChar(10)")]
		public string НомерСчётФактуры
		{
			get
			{
				return this._НомерСчётФактуры;
			}
			set
			{
				if ((this._НомерСчётФактуры != value))
				{
					this.OnНомерСчётФактурыChanging(value);
					this.SendPropertyChanging();
					this._НомерСчётФактуры = value;
					this.SendPropertyChanged("НомерСчётФактуры");
					this.OnНомерСчётФактурыChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ДатаСчётФактуры", DbType="Date")]
		public System.Nullable<System.DateTime> ДатаСчётФактуры
		{
			get
			{
				return this._ДатаСчётФактуры;
			}
			set
			{
				if ((this._ДатаСчётФактуры != value))
				{
					this.OnДатаСчётФактурыChanging(value);
					this.SendPropertyChanging();
					this._ДатаСчётФактуры = value;
					this.SendPropertyChanged("ДатаСчётФактуры");
					this.OnДатаСчётФактурыChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ДатаОплаты", DbType="VarChar(10)")]
		public string ДатаОплаты
		{
			get
			{
				return this._ДатаОплаты;
			}
			set
			{
				if ((this._ДатаОплаты != value))
				{
					this.OnДатаОплатыChanging(value);
					this.SendPropertyChanging();
					this._ДатаОплаты = value;
					this.SendPropertyChanged("ДатаОплаты");
					this.OnДатаОплатыChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logWrite", DbType="VarChar(150)")]
		public string logWrite
		{
			get
			{
				return this._logWrite;
			}
			set
			{
				if ((this._logWrite != value))
				{
					this.OnlogWriteChanging(value);
					this.SendPropertyChanging();
					this._logWrite = value;
					this.SendPropertyChanged("logWrite");
					this.OnlogWriteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logDate", DbType="NChar(12)")]
		public string logDate
		{
			get
			{
				return this._logDate;
			}
			set
			{
				if ((this._logDate != value))
				{
					this.OnlogDateChanging(value);
					this.SendPropertyChanging();
					this._logDate = value;
					this.SendPropertyChanged("logDate");
					this.OnlogDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Льготник")]
	public partial class Льготник : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_льготник;
		
		private string _Фамилия;
		
		private string _Имя;
		
		private string _Отчество;
		
		private System.Nullable<System.DateTime> _ДатаРождения;
		
		private string _улица;
		
		private string _НомерДома;
		
		private string _корпус;
		
		private string _НомерКвартиры;
		
		private string _СерияПаспорта;
		
		private string _НомерПаспорта;
		
		private System.Nullable<System.DateTime> _ДатаВыдачиПаспорта;
		
		private string _КемВыданПаспорт;
		
		private System.Nullable<int> _id_льготнойКатегории;
		
		private System.Nullable<int> _id_документ;
		
		private string _СерияДокумента;
		
		private string _НомерДокумента;
		
		private System.Nullable<System.DateTime> _ДатаВыдачиДокумента;
		
		private string _КемВыданДокумент;
		
		private int _id_область;
		
		private System.Nullable<int> _id_район;
		
		private System.Nullable<int> _id_насПункт;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_льготникChanging(int value);
    partial void Onid_льготникChanged();
    partial void OnФамилияChanging(string value);
    partial void OnФамилияChanged();
    partial void OnИмяChanging(string value);
    partial void OnИмяChanged();
    partial void OnОтчествоChanging(string value);
    partial void OnОтчествоChanged();
    partial void OnДатаРожденияChanging(System.Nullable<System.DateTime> value);
    partial void OnДатаРожденияChanged();
    partial void OnулицаChanging(string value);
    partial void OnулицаChanged();
    partial void OnНомерДомаChanging(string value);
    partial void OnНомерДомаChanged();
    partial void OnкорпусChanging(string value);
    partial void OnкорпусChanged();
    partial void OnНомерКвартирыChanging(string value);
    partial void OnНомерКвартирыChanged();
    partial void OnСерияПаспортаChanging(string value);
    partial void OnСерияПаспортаChanged();
    partial void OnНомерПаспортаChanging(string value);
    partial void OnНомерПаспортаChanged();
    partial void OnДатаВыдачиПаспортаChanging(System.Nullable<System.DateTime> value);
    partial void OnДатаВыдачиПаспортаChanged();
    partial void OnКемВыданПаспортChanging(string value);
    partial void OnКемВыданПаспортChanged();
    partial void Onid_льготнойКатегорииChanging(System.Nullable<int> value);
    partial void Onid_льготнойКатегорииChanged();
    partial void Onid_документChanging(System.Nullable<int> value);
    partial void Onid_документChanged();
    partial void OnСерияДокументаChanging(string value);
    partial void OnСерияДокументаChanged();
    partial void OnНомерДокументаChanging(string value);
    partial void OnНомерДокументаChanged();
    partial void OnДатаВыдачиДокументаChanging(System.Nullable<System.DateTime> value);
    partial void OnДатаВыдачиДокументаChanged();
    partial void OnКемВыданДокументChanging(string value);
    partial void OnКемВыданДокументChanged();
    partial void Onid_областьChanging(int value);
    partial void Onid_областьChanged();
    partial void Onid_районChanging(System.Nullable<int> value);
    partial void Onid_районChanged();
    partial void Onid_насПунктChanging(System.Nullable<int> value);
    partial void Onid_насПунктChanged();
    #endregion
		
		public Льготник()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_льготник", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_льготник
		{
			get
			{
				return this._id_льготник;
			}
			set
			{
				if ((this._id_льготник != value))
				{
					this.Onid_льготникChanging(value);
					this.SendPropertyChanging();
					this._id_льготник = value;
					this.SendPropertyChanged("id_льготник");
					this.Onid_льготникChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Фамилия", DbType="NVarChar(150)")]
		public string Фамилия
		{
			get
			{
				return this._Фамилия;
			}
			set
			{
				if ((this._Фамилия != value))
				{
					this.OnФамилияChanging(value);
					this.SendPropertyChanging();
					this._Фамилия = value;
					this.SendPropertyChanged("Фамилия");
					this.OnФамилияChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Имя", DbType="NVarChar(150)")]
		public string Имя
		{
			get
			{
				return this._Имя;
			}
			set
			{
				if ((this._Имя != value))
				{
					this.OnИмяChanging(value);
					this.SendPropertyChanging();
					this._Имя = value;
					this.SendPropertyChanged("Имя");
					this.OnИмяChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Отчество", DbType="NVarChar(150)")]
		public string Отчество
		{
			get
			{
				return this._Отчество;
			}
			set
			{
				if ((this._Отчество != value))
				{
					this.OnОтчествоChanging(value);
					this.SendPropertyChanging();
					this._Отчество = value;
					this.SendPropertyChanged("Отчество");
					this.OnОтчествоChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ДатаРождения", DbType="Date")]
		public System.Nullable<System.DateTime> ДатаРождения
		{
			get
			{
				return this._ДатаРождения;
			}
			set
			{
				if ((this._ДатаРождения != value))
				{
					this.OnДатаРожденияChanging(value);
					this.SendPropertyChanging();
					this._ДатаРождения = value;
					this.SendPropertyChanged("ДатаРождения");
					this.OnДатаРожденияChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_улица", DbType="NVarChar(200)")]
		public string улица
		{
			get
			{
				return this._улица;
			}
			set
			{
				if ((this._улица != value))
				{
					this.OnулицаChanging(value);
					this.SendPropertyChanging();
					this._улица = value;
					this.SendPropertyChanged("улица");
					this.OnулицаChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_НомерДома", DbType="NChar(10)")]
		public string НомерДома
		{
			get
			{
				return this._НомерДома;
			}
			set
			{
				if ((this._НомерДома != value))
				{
					this.OnНомерДомаChanging(value);
					this.SendPropertyChanging();
					this._НомерДома = value;
					this.SendPropertyChanged("НомерДома");
					this.OnНомерДомаChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_корпус", DbType="NChar(10)")]
		public string корпус
		{
			get
			{
				return this._корпус;
			}
			set
			{
				if ((this._корпус != value))
				{
					this.OnкорпусChanging(value);
					this.SendPropertyChanging();
					this._корпус = value;
					this.SendPropertyChanged("корпус");
					this.OnкорпусChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_НомерКвартиры", DbType="NChar(10)")]
		public string НомерКвартиры
		{
			get
			{
				return this._НомерКвартиры;
			}
			set
			{
				if ((this._НомерКвартиры != value))
				{
					this.OnНомерКвартирыChanging(value);
					this.SendPropertyChanging();
					this._НомерКвартиры = value;
					this.SendPropertyChanged("НомерКвартиры");
					this.OnНомерКвартирыChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_СерияПаспорта", DbType="NChar(10)")]
		public string СерияПаспорта
		{
			get
			{
				return this._СерияПаспорта;
			}
			set
			{
				if ((this._СерияПаспорта != value))
				{
					this.OnСерияПаспортаChanging(value);
					this.SendPropertyChanging();
					this._СерияПаспорта = value;
					this.SendPropertyChanged("СерияПаспорта");
					this.OnСерияПаспортаChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_НомерПаспорта", DbType="NChar(10)")]
		public string НомерПаспорта
		{
			get
			{
				return this._НомерПаспорта;
			}
			set
			{
				if ((this._НомерПаспорта != value))
				{
					this.OnНомерПаспортаChanging(value);
					this.SendPropertyChanging();
					this._НомерПаспорта = value;
					this.SendPropertyChanged("НомерПаспорта");
					this.OnНомерПаспортаChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ДатаВыдачиПаспорта", DbType="DateTime")]
		public System.Nullable<System.DateTime> ДатаВыдачиПаспорта
		{
			get
			{
				return this._ДатаВыдачиПаспорта;
			}
			set
			{
				if ((this._ДатаВыдачиПаспорта != value))
				{
					this.OnДатаВыдачиПаспортаChanging(value);
					this.SendPropertyChanging();
					this._ДатаВыдачиПаспорта = value;
					this.SendPropertyChanged("ДатаВыдачиПаспорта");
					this.OnДатаВыдачиПаспортаChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_КемВыданПаспорт", DbType="NVarChar(500)")]
		public string КемВыданПаспорт
		{
			get
			{
				return this._КемВыданПаспорт;
			}
			set
			{
				if ((this._КемВыданПаспорт != value))
				{
					this.OnКемВыданПаспортChanging(value);
					this.SendPropertyChanging();
					this._КемВыданПаспорт = value;
					this.SendPropertyChanged("КемВыданПаспорт");
					this.OnКемВыданПаспортChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_льготнойКатегории", DbType="Int")]
		public System.Nullable<int> id_льготнойКатегории
		{
			get
			{
				return this._id_льготнойКатегории;
			}
			set
			{
				if ((this._id_льготнойКатегории != value))
				{
					this.Onid_льготнойКатегорииChanging(value);
					this.SendPropertyChanging();
					this._id_льготнойКатегории = value;
					this.SendPropertyChanged("id_льготнойКатегории");
					this.Onid_льготнойКатегорииChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_документ", DbType="Int")]
		public System.Nullable<int> id_документ
		{
			get
			{
				return this._id_документ;
			}
			set
			{
				if ((this._id_документ != value))
				{
					this.Onid_документChanging(value);
					this.SendPropertyChanging();
					this._id_документ = value;
					this.SendPropertyChanged("id_документ");
					this.Onid_документChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_СерияДокумента", DbType="NChar(30)")]
		public string СерияДокумента
		{
			get
			{
				return this._СерияДокумента;
			}
			set
			{
				if ((this._СерияДокумента != value))
				{
					this.OnСерияДокументаChanging(value);
					this.SendPropertyChanging();
					this._СерияДокумента = value;
					this.SendPropertyChanged("СерияДокумента");
					this.OnСерияДокументаChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_НомерДокумента", DbType="NChar(10)")]
		public string НомерДокумента
		{
			get
			{
				return this._НомерДокумента;
			}
			set
			{
				if ((this._НомерДокумента != value))
				{
					this.OnНомерДокументаChanging(value);
					this.SendPropertyChanging();
					this._НомерДокумента = value;
					this.SendPropertyChanged("НомерДокумента");
					this.OnНомерДокументаChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ДатаВыдачиДокумента", DbType="DateTime")]
		public System.Nullable<System.DateTime> ДатаВыдачиДокумента
		{
			get
			{
				return this._ДатаВыдачиДокумента;
			}
			set
			{
				if ((this._ДатаВыдачиДокумента != value))
				{
					this.OnДатаВыдачиДокументаChanging(value);
					this.SendPropertyChanging();
					this._ДатаВыдачиДокумента = value;
					this.SendPropertyChanged("ДатаВыдачиДокумента");
					this.OnДатаВыдачиДокументаChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_КемВыданДокумент", DbType="NVarChar(500)")]
		public string КемВыданДокумент
		{
			get
			{
				return this._КемВыданДокумент;
			}
			set
			{
				if ((this._КемВыданДокумент != value))
				{
					this.OnКемВыданДокументChanging(value);
					this.SendPropertyChanging();
					this._КемВыданДокумент = value;
					this.SendPropertyChanged("КемВыданДокумент");
					this.OnКемВыданДокументChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_область", DbType="Int NOT NULL")]
		public int id_область
		{
			get
			{
				return this._id_область;
			}
			set
			{
				if ((this._id_область != value))
				{
					this.Onid_областьChanging(value);
					this.SendPropertyChanging();
					this._id_область = value;
					this.SendPropertyChanged("id_область");
					this.Onid_областьChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_район", DbType="Int")]
		public System.Nullable<int> id_район
		{
			get
			{
				return this._id_район;
			}
			set
			{
				if ((this._id_район != value))
				{
					this.Onid_районChanging(value);
					this.SendPropertyChanging();
					this._id_район = value;
					this.SendPropertyChanged("id_район");
					this.Onid_районChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_насПункт", DbType="Int")]
		public System.Nullable<int> id_насПункт
		{
			get
			{
				return this._id_насПункт;
			}
			set
			{
				if ((this._id_насПункт != value))
				{
					this.Onid_насПунктChanging(value);
					this.SendPropertyChanging();
					this._id_насПункт = value;
					this.SendPropertyChanged("id_насПункт");
					this.Onid_насПунктChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.УслугиПоДоговору")]
	public partial class УслугиПоДоговору : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_услугиДоговор;
		
		private string _НаименованиеУслуги;
		
		private System.Nullable<decimal> _цена;
		
		private System.Nullable<int> _Количество;
		
		private System.Nullable<int> _id_договор;
		
		private string _НомерПоПеречню;
		
		private System.Nullable<decimal> _Сумма;
		
		private System.Nullable<int> _ТехЛист;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_услугиДоговорChanging(int value);
    partial void Onid_услугиДоговорChanged();
    partial void OnНаименованиеУслугиChanging(string value);
    partial void OnНаименованиеУслугиChanged();
    partial void OnценаChanging(System.Nullable<decimal> value);
    partial void OnценаChanged();
    partial void OnКоличествоChanging(System.Nullable<int> value);
    partial void OnКоличествоChanged();
    partial void Onid_договорChanging(System.Nullable<int> value);
    partial void Onid_договорChanged();
    partial void OnНомерПоПеречнюChanging(string value);
    partial void OnНомерПоПеречнюChanged();
    partial void OnСуммаChanging(System.Nullable<decimal> value);
    partial void OnСуммаChanged();
    partial void OnТехЛистChanging(System.Nullable<int> value);
    partial void OnТехЛистChanged();
    #endregion
		
		public УслугиПоДоговору()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_услугиДоговор", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_услугиДоговор
		{
			get
			{
				return this._id_услугиДоговор;
			}
			set
			{
				if ((this._id_услугиДоговор != value))
				{
					this.Onid_услугиДоговорChanging(value);
					this.SendPropertyChanging();
					this._id_услугиДоговор = value;
					this.SendPropertyChanged("id_услугиДоговор");
					this.Onid_услугиДоговорChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_НаименованиеУслуги", DbType="NVarChar(300)")]
		public string НаименованиеУслуги
		{
			get
			{
				return this._НаименованиеУслуги;
			}
			set
			{
				if ((this._НаименованиеУслуги != value))
				{
					this.OnНаименованиеУслугиChanging(value);
					this.SendPropertyChanging();
					this._НаименованиеУслуги = value;
					this.SendPropertyChanged("НаименованиеУслуги");
					this.OnНаименованиеУслугиChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_цена", DbType="Money")]
		public System.Nullable<decimal> цена
		{
			get
			{
				return this._цена;
			}
			set
			{
				if ((this._цена != value))
				{
					this.OnценаChanging(value);
					this.SendPropertyChanging();
					this._цена = value;
					this.SendPropertyChanged("цена");
					this.OnценаChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Количество", DbType="Int")]
		public System.Nullable<int> Количество
		{
			get
			{
				return this._Количество;
			}
			set
			{
				if ((this._Количество != value))
				{
					this.OnКоличествоChanging(value);
					this.SendPropertyChanging();
					this._Количество = value;
					this.SendPropertyChanged("Количество");
					this.OnКоличествоChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_договор", DbType="Int")]
		public System.Nullable<int> id_договор
		{
			get
			{
				return this._id_договор;
			}
			set
			{
				if ((this._id_договор != value))
				{
					this.Onid_договорChanging(value);
					this.SendPropertyChanging();
					this._id_договор = value;
					this.SendPropertyChanged("id_договор");
					this.Onid_договорChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_НомерПоПеречню", DbType="NChar(50)")]
		public string НомерПоПеречню
		{
			get
			{
				return this._НомерПоПеречню;
			}
			set
			{
				if ((this._НомерПоПеречню != value))
				{
					this.OnНомерПоПеречнюChanging(value);
					this.SendPropertyChanging();
					this._НомерПоПеречню = value;
					this.SendPropertyChanged("НомерПоПеречню");
					this.OnНомерПоПеречнюChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Сумма", DbType="Money")]
		public System.Nullable<decimal> Сумма
		{
			get
			{
				return this._Сумма;
			}
			set
			{
				if ((this._Сумма != value))
				{
					this.OnСуммаChanging(value);
					this.SendPropertyChanging();
					this._Сумма = value;
					this.SendPropertyChanged("Сумма");
					this.OnСуммаChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ТехЛист", DbType="Int")]
		public System.Nullable<int> ТехЛист
		{
			get
			{
				return this._ТехЛист;
			}
			set
			{
				if ((this._ТехЛист != value))
				{
					this.OnТехЛистChanging(value);
					this.SendPropertyChanging();
					this._ТехЛист = value;
					this.SendPropertyChanged("ТехЛист");
					this.OnТехЛистChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Поликлинника")]
	public partial class Поликлинника : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_поликлинника;
		
		private string _НаименованиеПоликлинники;
		
		private string _КодПоликлинники;
		
		private string _ЮридическийАдрес;
		
		private string _ФактическийАдрес;
		
		private System.Nullable<int> _id_главВрач;
		
		private System.Nullable<int> _id_главБух;
		
		private string _СвидетельствоРегистрации;
		
		private string _ИНН;
		
		private string _КПП;
		
		private string _БИК;
		
		private string _НаименованиеБанка;
		
		private string _РасчётныйСчёт;
		
		private string _ЛицевойСчёт;
		
		private string _НомерЛицензии;
		
		private System.Nullable<System.DateTime> _ДатаРегистрацииЛицензии;
		
		private string _ОГРН;
		
		private string _СвидетельствоРегистрацииЕГРЮЛ;
		
		private string _ОрганВыдавшийЛицензию;
		
		private string _Постановление;
		
		private string _ОКПО;
		
		private string _ОКАТО;
		
		private System.Nullable<int> _Flag;
		
		private System.Nullable<int> _НачальныйНомерДоговора;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_поликлинникаChanging(int value);
    partial void Onid_поликлинникаChanged();
    partial void OnНаименованиеПоликлинникиChanging(string value);
    partial void OnНаименованиеПоликлинникиChanged();
    partial void OnКодПоликлинникиChanging(string value);
    partial void OnКодПоликлинникиChanged();
    partial void OnЮридическийАдресChanging(string value);
    partial void OnЮридическийАдресChanged();
    partial void OnФактическийАдресChanging(string value);
    partial void OnФактическийАдресChanged();
    partial void Onid_главВрачChanging(System.Nullable<int> value);
    partial void Onid_главВрачChanged();
    partial void Onid_главБухChanging(System.Nullable<int> value);
    partial void Onid_главБухChanged();
    partial void OnСвидетельствоРегистрацииChanging(string value);
    partial void OnСвидетельствоРегистрацииChanged();
    partial void OnИННChanging(string value);
    partial void OnИННChanged();
    partial void OnКППChanging(string value);
    partial void OnКППChanged();
    partial void OnБИКChanging(string value);
    partial void OnБИКChanged();
    partial void OnНаименованиеБанкаChanging(string value);
    partial void OnНаименованиеБанкаChanged();
    partial void OnРасчётныйСчётChanging(string value);
    partial void OnРасчётныйСчётChanged();
    partial void OnЛицевойСчётChanging(string value);
    partial void OnЛицевойСчётChanged();
    partial void OnНомерЛицензииChanging(string value);
    partial void OnНомерЛицензииChanged();
    partial void OnДатаРегистрацииЛицензииChanging(System.Nullable<System.DateTime> value);
    partial void OnДатаРегистрацииЛицензииChanged();
    partial void OnОГРНChanging(string value);
    partial void OnОГРНChanged();
    partial void OnСвидетельствоРегистрацииЕГРЮЛChanging(string value);
    partial void OnСвидетельствоРегистрацииЕГРЮЛChanged();
    partial void OnОрганВыдавшийЛицензиюChanging(string value);
    partial void OnОрганВыдавшийЛицензиюChanged();
    partial void OnПостановлениеChanging(string value);
    partial void OnПостановлениеChanged();
    partial void OnОКПОChanging(string value);
    partial void OnОКПОChanged();
    partial void OnОКАТОChanging(string value);
    partial void OnОКАТОChanged();
    partial void OnFlagChanging(System.Nullable<int> value);
    partial void OnFlagChanged();
    partial void OnНачальныйНомерДоговораChanging(System.Nullable<int> value);
    partial void OnНачальныйНомерДоговораChanged();
    #endregion
		
		public Поликлинника()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_поликлинника", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_поликлинника
		{
			get
			{
				return this._id_поликлинника;
			}
			set
			{
				if ((this._id_поликлинника != value))
				{
					this.Onid_поликлинникаChanging(value);
					this.SendPropertyChanging();
					this._id_поликлинника = value;
					this.SendPropertyChanged("id_поликлинника");
					this.Onid_поликлинникаChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_НаименованиеПоликлинники", DbType="NVarChar(300)")]
		public string НаименованиеПоликлинники
		{
			get
			{
				return this._НаименованиеПоликлинники;
			}
			set
			{
				if ((this._НаименованиеПоликлинники != value))
				{
					this.OnНаименованиеПоликлинникиChanging(value);
					this.SendPropertyChanging();
					this._НаименованиеПоликлинники = value;
					this.SendPropertyChanged("НаименованиеПоликлинники");
					this.OnНаименованиеПоликлинникиChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_КодПоликлинники", DbType="NChar(10)")]
		public string КодПоликлинники
		{
			get
			{
				return this._КодПоликлинники;
			}
			set
			{
				if ((this._КодПоликлинники != value))
				{
					this.OnКодПоликлинникиChanging(value);
					this.SendPropertyChanging();
					this._КодПоликлинники = value;
					this.SendPropertyChanged("КодПоликлинники");
					this.OnКодПоликлинникиChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ЮридическийАдрес", DbType="NVarChar(500)")]
		public string ЮридическийАдрес
		{
			get
			{
				return this._ЮридическийАдрес;
			}
			set
			{
				if ((this._ЮридическийАдрес != value))
				{
					this.OnЮридическийАдресChanging(value);
					this.SendPropertyChanging();
					this._ЮридическийАдрес = value;
					this.SendPropertyChanged("ЮридическийАдрес");
					this.OnЮридическийАдресChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ФактическийАдрес", DbType="NVarChar(500)")]
		public string ФактическийАдрес
		{
			get
			{
				return this._ФактическийАдрес;
			}
			set
			{
				if ((this._ФактическийАдрес != value))
				{
					this.OnФактическийАдресChanging(value);
					this.SendPropertyChanging();
					this._ФактическийАдрес = value;
					this.SendPropertyChanged("ФактическийАдрес");
					this.OnФактическийАдресChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_главВрач", DbType="Int")]
		public System.Nullable<int> id_главВрач
		{
			get
			{
				return this._id_главВрач;
			}
			set
			{
				if ((this._id_главВрач != value))
				{
					this.Onid_главВрачChanging(value);
					this.SendPropertyChanging();
					this._id_главВрач = value;
					this.SendPropertyChanged("id_главВрач");
					this.Onid_главВрачChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_главБух", DbType="Int")]
		public System.Nullable<int> id_главБух
		{
			get
			{
				return this._id_главБух;
			}
			set
			{
				if ((this._id_главБух != value))
				{
					this.Onid_главБухChanging(value);
					this.SendPropertyChanging();
					this._id_главБух = value;
					this.SendPropertyChanged("id_главБух");
					this.Onid_главБухChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_СвидетельствоРегистрации", DbType="NChar(30)")]
		public string СвидетельствоРегистрации
		{
			get
			{
				return this._СвидетельствоРегистрации;
			}
			set
			{
				if ((this._СвидетельствоРегистрации != value))
				{
					this.OnСвидетельствоРегистрацииChanging(value);
					this.SendPropertyChanging();
					this._СвидетельствоРегистрации = value;
					this.SendPropertyChanged("СвидетельствоРегистрации");
					this.OnСвидетельствоРегистрацииChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ИНН", DbType="NChar(20)")]
		public string ИНН
		{
			get
			{
				return this._ИНН;
			}
			set
			{
				if ((this._ИНН != value))
				{
					this.OnИННChanging(value);
					this.SendPropertyChanging();
					this._ИНН = value;
					this.SendPropertyChanged("ИНН");
					this.OnИННChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_КПП", DbType="NChar(20)")]
		public string КПП
		{
			get
			{
				return this._КПП;
			}
			set
			{
				if ((this._КПП != value))
				{
					this.OnКППChanging(value);
					this.SendPropertyChanging();
					this._КПП = value;
					this.SendPropertyChanged("КПП");
					this.OnКППChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_БИК", DbType="NChar(20)")]
		public string БИК
		{
			get
			{
				return this._БИК;
			}
			set
			{
				if ((this._БИК != value))
				{
					this.OnБИКChanging(value);
					this.SendPropertyChanging();
					this._БИК = value;
					this.SendPropertyChanged("БИК");
					this.OnБИКChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_НаименованиеБанка", DbType="NVarChar(200)")]
		public string НаименованиеБанка
		{
			get
			{
				return this._НаименованиеБанка;
			}
			set
			{
				if ((this._НаименованиеБанка != value))
				{
					this.OnНаименованиеБанкаChanging(value);
					this.SendPropertyChanging();
					this._НаименованиеБанка = value;
					this.SendPropertyChanged("НаименованиеБанка");
					this.OnНаименованиеБанкаChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_РасчётныйСчёт", DbType="NChar(20)")]
		public string РасчётныйСчёт
		{
			get
			{
				return this._РасчётныйСчёт;
			}
			set
			{
				if ((this._РасчётныйСчёт != value))
				{
					this.OnРасчётныйСчётChanging(value);
					this.SendPropertyChanging();
					this._РасчётныйСчёт = value;
					this.SendPropertyChanged("РасчётныйСчёт");
					this.OnРасчётныйСчётChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ЛицевойСчёт", DbType="NChar(10)")]
		public string ЛицевойСчёт
		{
			get
			{
				return this._ЛицевойСчёт;
			}
			set
			{
				if ((this._ЛицевойСчёт != value))
				{
					this.OnЛицевойСчётChanging(value);
					this.SendPropertyChanging();
					this._ЛицевойСчёт = value;
					this.SendPropertyChanged("ЛицевойСчёт");
					this.OnЛицевойСчётChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_НомерЛицензии", DbType="NChar(20)")]
		public string НомерЛицензии
		{
			get
			{
				return this._НомерЛицензии;
			}
			set
			{
				if ((this._НомерЛицензии != value))
				{
					this.OnНомерЛицензииChanging(value);
					this.SendPropertyChanging();
					this._НомерЛицензии = value;
					this.SendPropertyChanged("НомерЛицензии");
					this.OnНомерЛицензииChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ДатаРегистрацииЛицензии", DbType="DateTime")]
		public System.Nullable<System.DateTime> ДатаРегистрацииЛицензии
		{
			get
			{
				return this._ДатаРегистрацииЛицензии;
			}
			set
			{
				if ((this._ДатаРегистрацииЛицензии != value))
				{
					this.OnДатаРегистрацииЛицензииChanging(value);
					this.SendPropertyChanging();
					this._ДатаРегистрацииЛицензии = value;
					this.SendPropertyChanged("ДатаРегистрацииЛицензии");
					this.OnДатаРегистрацииЛицензииChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ОГРН", DbType="NChar(20)")]
		public string ОГРН
		{
			get
			{
				return this._ОГРН;
			}
			set
			{
				if ((this._ОГРН != value))
				{
					this.OnОГРНChanging(value);
					this.SendPropertyChanging();
					this._ОГРН = value;
					this.SendPropertyChanged("ОГРН");
					this.OnОГРНChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_СвидетельствоРегистрацииЕГРЮЛ", DbType="NChar(255)")]
		public string СвидетельствоРегистрацииЕГРЮЛ
		{
			get
			{
				return this._СвидетельствоРегистрацииЕГРЮЛ;
			}
			set
			{
				if ((this._СвидетельствоРегистрацииЕГРЮЛ != value))
				{
					this.OnСвидетельствоРегистрацииЕГРЮЛChanging(value);
					this.SendPropertyChanging();
					this._СвидетельствоРегистрацииЕГРЮЛ = value;
					this.SendPropertyChanged("СвидетельствоРегистрацииЕГРЮЛ");
					this.OnСвидетельствоРегистрацииЕГРЮЛChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ОрганВыдавшийЛицензию", DbType="NChar(255)")]
		public string ОрганВыдавшийЛицензию
		{
			get
			{
				return this._ОрганВыдавшийЛицензию;
			}
			set
			{
				if ((this._ОрганВыдавшийЛицензию != value))
				{
					this.OnОрганВыдавшийЛицензиюChanging(value);
					this.SendPropertyChanging();
					this._ОрганВыдавшийЛицензию = value;
					this.SendPropertyChanged("ОрганВыдавшийЛицензию");
					this.OnОрганВыдавшийЛицензиюChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Постановление", DbType="NVarChar(MAX)")]
		public string Постановление
		{
			get
			{
				return this._Постановление;
			}
			set
			{
				if ((this._Постановление != value))
				{
					this.OnПостановлениеChanging(value);
					this.SendPropertyChanging();
					this._Постановление = value;
					this.SendPropertyChanged("Постановление");
					this.OnПостановлениеChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ОКПО", DbType="NChar(50)")]
		public string ОКПО
		{
			get
			{
				return this._ОКПО;
			}
			set
			{
				if ((this._ОКПО != value))
				{
					this.OnОКПОChanging(value);
					this.SendPropertyChanging();
					this._ОКПО = value;
					this.SendPropertyChanged("ОКПО");
					this.OnОКПОChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ОКАТО", DbType="NChar(50)")]
		public string ОКАТО
		{
			get
			{
				return this._ОКАТО;
			}
			set
			{
				if ((this._ОКАТО != value))
				{
					this.OnОКАТОChanging(value);
					this.SendPropertyChanging();
					this._ОКАТО = value;
					this.SendPropertyChanged("ОКАТО");
					this.OnОКАТОChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Flag", DbType="Int")]
		public System.Nullable<int> Flag
		{
			get
			{
				return this._Flag;
			}
			set
			{
				if ((this._Flag != value))
				{
					this.OnFlagChanging(value);
					this.SendPropertyChanging();
					this._Flag = value;
					this.SendPropertyChanged("Flag");
					this.OnFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_НачальныйНомерДоговора", DbType="Int")]
		public System.Nullable<int> НачальныйНомерДоговора
		{
			get
			{
				return this._НачальныйНомерДоговора;
			}
			set
			{
				if ((this._НачальныйНомерДоговора != value))
				{
					this.OnНачальныйНомерДоговораChanging(value);
					this.SendPropertyChanging();
					this._НачальныйНомерДоговора = value;
					this.SendPropertyChanged("НачальныйНомерДоговора");
					this.OnНачальныйНомерДоговораChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ЛьготнаяКатегория")]
	public partial class ЛьготнаяКатегория : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_льготнойКатегории;
		
		private string _ЛьготнаяКатегория1;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_льготнойКатегорииChanging(int value);
    partial void Onid_льготнойКатегорииChanged();
    partial void OnЛьготнаяКатегория1Changing(string value);
    partial void OnЛьготнаяКатегория1Changed();
    #endregion
		
		public ЛьготнаяКатегория()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_льготнойКатегории", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_льготнойКатегории
		{
			get
			{
				return this._id_льготнойКатегории;
			}
			set
			{
				if ((this._id_льготнойКатегории != value))
				{
					this.Onid_льготнойКатегорииChanging(value);
					this.SendPropertyChanging();
					this._id_льготнойКатегории = value;
					this.SendPropertyChanged("id_льготнойКатегории");
					this.Onid_льготнойКатегорииChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ЛьготнаяКатегория", Storage="_ЛьготнаяКатегория1", DbType="NChar(200)")]
		public string ЛьготнаяКатегория1
		{
			get
			{
				return this._ЛьготнаяКатегория1;
			}
			set
			{
				if ((this._ЛьготнаяКатегория1 != value))
				{
					this.OnЛьготнаяКатегория1Changing(value);
					this.SendPropertyChanging();
					this._ЛьготнаяКатегория1 = value;
					this.SendPropertyChanged("ЛьготнаяКатегория1");
					this.OnЛьготнаяКатегория1Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ТипДокумента")]
	public partial class ТипДокумента : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_документ;
		
		private string _НаименованиеТипаДокумента;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_документChanging(int value);
    partial void Onid_документChanged();
    partial void OnНаименованиеТипаДокументаChanging(string value);
    partial void OnНаименованиеТипаДокументаChanged();
    #endregion
		
		public ТипДокумента()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_документ", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_документ
		{
			get
			{
				return this._id_документ;
			}
			set
			{
				if ((this._id_документ != value))
				{
					this.Onid_документChanging(value);
					this.SendPropertyChanging();
					this._id_документ = value;
					this.SendPropertyChanged("id_документ");
					this.Onid_документChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_НаименованиеТипаДокумента", DbType="NChar(255)")]
		public string НаименованиеТипаДокумента
		{
			get
			{
				return this._НаименованиеТипаДокумента;
			}
			set
			{
				if ((this._НаименованиеТипаДокумента != value))
				{
					this.OnНаименованиеТипаДокументаChanging(value);
					this.SendPropertyChanging();
					this._НаименованиеТипаДокумента = value;
					this.SendPropertyChanged("НаименованиеТипаДокумента");
					this.OnНаименованиеТипаДокументаChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.НаселённыйПункт")]
	public partial class НаселённыйПункт : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_насПункт;
		
		private string _Наименование;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_насПунктChanging(int value);
    partial void Onid_насПунктChanged();
    partial void OnНаименованиеChanging(string value);
    partial void OnНаименованиеChanged();
    #endregion
		
		public НаселённыйПункт()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_насПункт", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_насПункт
		{
			get
			{
				return this._id_насПункт;
			}
			set
			{
				if ((this._id_насПункт != value))
				{
					this.Onid_насПунктChanging(value);
					this.SendPropertyChanging();
					this._id_насПункт = value;
					this.SendPropertyChanged("id_насПункт");
					this.Onid_насПунктChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Наименование", DbType="NChar(250)")]
		public string Наименование
		{
			get
			{
				return this._Наименование;
			}
			set
			{
				if ((this._Наименование != value))
				{
					this.OnНаименованиеChanging(value);
					this.SendPropertyChanging();
					this._Наименование = value;
					this.SendPropertyChanged("Наименование");
					this.OnНаименованиеChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.НаименованиеРайона")]
	public partial class НаименованиеРайона : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_район;
		
		private string _РайонОбласти;
		
		private System.Nullable<int> _id_террОргана;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_районChanging(int value);
    partial void Onid_районChanged();
    partial void OnРайонОбластиChanging(string value);
    partial void OnРайонОбластиChanged();
    partial void Onid_террОрганаChanging(System.Nullable<int> value);
    partial void Onid_террОрганаChanged();
    #endregion
		
		public НаименованиеРайона()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_район", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_район
		{
			get
			{
				return this._id_район;
			}
			set
			{
				if ((this._id_район != value))
				{
					this.Onid_районChanging(value);
					this.SendPropertyChanging();
					this._id_район = value;
					this.SendPropertyChanged("id_район");
					this.Onid_районChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_РайонОбласти", DbType="NChar(200)")]
		public string РайонОбласти
		{
			get
			{
				return this._РайонОбласти;
			}
			set
			{
				if ((this._РайонОбласти != value))
				{
					this.OnРайонОбластиChanging(value);
					this.SendPropertyChanging();
					this._РайонОбласти = value;
					this.SendPropertyChanged("РайонОбласти");
					this.OnРайонОбластиChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_террОргана", DbType="Int")]
		public System.Nullable<int> id_террОргана
		{
			get
			{
				return this._id_террОргана;
			}
			set
			{
				if ((this._id_террОргана != value))
				{
					this.Onid_террОрганаChanging(value);
					this.SendPropertyChanging();
					this._id_террОргана = value;
					this.SendPropertyChanged("id_террОргана");
					this.Onid_террОрганаChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
