#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlDantist.Repository
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Dentists")]
	public partial class DataClasses2DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    #endregion
		
		public DataClasses2DataContext() : 
				base(global::ControlDantist.Properties.Settings.Default.DentistsConnectionString3, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses2DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ViewPersonVipNet3> ViewPersonVipNet3
		{
			get
			{
				return this.GetTable<ViewPersonVipNet3>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ViewPersonVipNet3")]
	public partial class ViewPersonVipNet3
	{
		
		private int _id_льготник;
		
		private string _Фамилия;
		
		private string _Имя;
		
		private string _Отчество;
		
		private System.Nullable<System.DateTime> _ДатаРождения;
		
		private string _Улица;
		
		private string _НомерДома;
		
		private string _корпус;
		
		private string _НомерКвартиры;
		
		private string _СерияДокумента;
		
		private string _НомерДокумента;
		
		private System.Nullable<decimal> _СуммаАктаВыполненныхРабот;
		
		private System.Nullable<System.DateTime> _ДатаАкта;
		
		private System.Nullable<int> _id_район;
		
		private string _Наименование;
		
		private string _NameRegion;
		
		private int _id_насПункт;
		
		private string _НомерАкта;
		
		private System.Nullable<System.DateTime> _ДатаПодписания;
		
		public ViewPersonVipNet3()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_льготник", DbType="Int NOT NULL")]
		public int id_льготник
		{
			get
			{
				return this._id_льготник;
			}
			set
			{
				if ((this._id_льготник != value))
				{
					this._id_льготник = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Фамилия", DbType="NVarChar(150)")]
		public string Фамилия
		{
			get
			{
				return this._Фамилия;
			}
			set
			{
				if ((this._Фамилия != value))
				{
					this._Фамилия = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Имя", DbType="NVarChar(150)")]
		public string Имя
		{
			get
			{
				return this._Имя;
			}
			set
			{
				if ((this._Имя != value))
				{
					this._Имя = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Отчество", DbType="NVarChar(150)")]
		public string Отчество
		{
			get
			{
				return this._Отчество;
			}
			set
			{
				if ((this._Отчество != value))
				{
					this._Отчество = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ДатаРождения", DbType="Date")]
		public System.Nullable<System.DateTime> ДатаРождения
		{
			get
			{
				return this._ДатаРождения;
			}
			set
			{
				if ((this._ДатаРождения != value))
				{
					this._ДатаРождения = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Улица", DbType="NVarChar(200)")]
		public string Улица
		{
			get
			{
				return this._Улица;
			}
			set
			{
				if ((this._Улица != value))
				{
					this._Улица = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_НомерДома", DbType="NChar(10)")]
		public string НомерДома
		{
			get
			{
				return this._НомерДома;
			}
			set
			{
				if ((this._НомерДома != value))
				{
					this._НомерДома = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_корпус", DbType="NChar(10)")]
		public string корпус
		{
			get
			{
				return this._корпус;
			}
			set
			{
				if ((this._корпус != value))
				{
					this._корпус = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_НомерКвартиры", DbType="NChar(40)")]
		public string НомерКвартиры
		{
			get
			{
				return this._НомерКвартиры;
			}
			set
			{
				if ((this._НомерКвартиры != value))
				{
					this._НомерКвартиры = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_СерияДокумента", DbType="NChar(50)")]
		public string СерияДокумента
		{
			get
			{
				return this._СерияДокумента;
			}
			set
			{
				if ((this._СерияДокумента != value))
				{
					this._СерияДокумента = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_НомерДокумента", DbType="NChar(50)")]
		public string НомерДокумента
		{
			get
			{
				return this._НомерДокумента;
			}
			set
			{
				if ((this._НомерДокумента != value))
				{
					this._НомерДокумента = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_СуммаАктаВыполненныхРабот", DbType="Money")]
		public System.Nullable<decimal> СуммаАктаВыполненныхРабот
		{
			get
			{
				return this._СуммаАктаВыполненныхРабот;
			}
			set
			{
				if ((this._СуммаАктаВыполненныхРабот != value))
				{
					this._СуммаАктаВыполненныхРабот = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ДатаАкта", DbType="DateTime")]
		public System.Nullable<System.DateTime> ДатаАкта
		{
			get
			{
				return this._ДатаАкта;
			}
			set
			{
				if ((this._ДатаАкта != value))
				{
					this._ДатаАкта = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_район", DbType="Int")]
		public System.Nullable<int> id_район
		{
			get
			{
				return this._id_район;
			}
			set
			{
				if ((this._id_район != value))
				{
					this._id_район = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Наименование", DbType="NChar(250)")]
		public string Наименование
		{
			get
			{
				return this._Наименование;
			}
			set
			{
				if ((this._Наименование != value))
				{
					this._Наименование = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameRegion", DbType="NVarChar(80)")]
		public string NameRegion
		{
			get
			{
				return this._NameRegion;
			}
			set
			{
				if ((this._NameRegion != value))
				{
					this._NameRegion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_насПункт", DbType="Int NOT NULL")]
		public int id_насПункт
		{
			get
			{
				return this._id_насПункт;
			}
			set
			{
				if ((this._id_насПункт != value))
				{
					this._id_насПункт = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_НомерАкта", DbType="NVarChar(100)")]
		public string НомерАкта
		{
			get
			{
				return this._НомерАкта;
			}
			set
			{
				if ((this._НомерАкта != value))
				{
					this._НомерАкта = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ДатаПодписания", DbType="DateTime")]
		public System.Nullable<System.DateTime> ДатаПодписания
		{
			get
			{
				return this._ДатаПодписания;
			}
			set
			{
				if ((this._ДатаПодписания != value))
				{
					this._ДатаПодписания = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
