<?xml version="1.0" encoding="utf-8"?><Database Name="Dentists" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=10.159.102.21;Initial Catalog=Dentists;User ID=admin_dantist" SettingsObjectName="ControlDantist.Properties.Settings" SettingsPropertyName="DentistsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ListNumbersProgectsReestr" Member="ListNumbersProgectsReestr">
    <Type Name="ListNumbersProgectsReestr">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdProjectRegistrFiles" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NumberContract" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="SummaContract" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="FIO" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Льготник" Member="Льготник">
    <Type Name="Льготник">
      <Column Name="id_льготник" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Фамилия" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Имя" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Отчество" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="ДатаРождения" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="улица" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="НомерДома" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="корпус" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="НомерКвартиры" Type="System.String" DbType="NChar(40)" CanBeNull="true" />
      <Column Name="СерияПаспорта" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="НомерПаспорта" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="ДатаВыдачиПаспорта" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="КемВыданПаспорт" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="id_льготнойКатегории" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_документ" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="СерияДокумента" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="НомерДокумента" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="ДатаВыдачиДокумента" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="КемВыданДокумент" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="id_область" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_район" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_насПункт" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Снилс" Type="System.String" DbType="NVarChar(11)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.РайонОбласти" Member="РайонОбласти">
    <Type Name="РайонОбласти">
      <Column Name="idRegion" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NameRegion" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ЛьготнаяКатегория" Member="ЛьготнаяКатегория">
    <Type Name="ЛьготнаяКатегория">
      <Column Name="id_льготнойКатегории" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ЛьготнаяКатегория" Member="ЛьготнаяКатегория1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LimitPreferenceCategory" Member="LimitPreferenceCategory">
    <Type Name="LimitPreferenceCategory">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idLimitMoney" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_льготнойКатегории" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Year" Member="Year">
    <Type Name="Year">
      <Column Name="intYear" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Year" Member="Year1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.LimittMoney" Member="LimittMoney">
    <Type Name="LimittMoney">
      <Column Name="idLimitMoney" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Limit" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="idYear" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ViewDisplayLimit" Member="ViewDisplayLimit">
    <Type Name="ViewDisplayLimit">
      <Column Name="id_льготнойКатегории" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ЛьготнаяКатегория" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Limit" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="idLimitMoney" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Year" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ViewЛьготникДоговорРеестр" Member="ViewЛьготникДоговорРеестр">
    <Type Name="ViewЛьготникДоговорРеестр">
      <Column Name="Фамилия" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Имя" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Отчество" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="ДатаРождения" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="СерияДокумента" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="НомерДокумента" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="СерияПаспорта" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="НомерПаспорта" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="idFileRegistProgect" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="flagОжиданиеПроверки" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="НомерДоговора" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="ДатаВыдачиПаспорта" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ДатаВыдачиДокумента" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="id_договор" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.НаселённыйПункт" Member="НаселённыйПункт">
    <Type Name="НаселённыйПункт">
      <Column Name="id_насПункт" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Наименование" Type="System.String" DbType="NChar(250)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Лист1$" Member="Лист1_">
    <Type Name="Лист1_">
      <Column Name="F1" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="F2" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="F3" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ФИО" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ViewАктДоговор" Member="ViewАктДоговор">
    <Type Name="ViewАктДоговор">
      <Column Name="НомерАкта" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="ДатаАктаВыполненныхРабот" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="НомерДоговора" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="id_договор" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_льготник" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ФлагПроверки" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Договор" Member="Договор">
    <Type Name="Договор">
      <Column Name="id_договор" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="НомерДоговора" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="ДатаДоговора" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ДатаАктаВыполненныхРабот" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="СуммаАктаВыполненныхРабот" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="id_льготнаяКатегория" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_поликлинника" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Примечание" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="id_комитет" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ФлагНаличияДоговора" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ФлагНаличияАкта" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="id_льготник" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ФлагДопСоглашения" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="флагСРН" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="флагУслуги" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="датаВозврата" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ДатаЗаписиДоговора" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ФлагПроверки" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="НомерРеестра" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="ДатаРеестра" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="НомерСчётФактрура" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="ДатаСчётФактура" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="flagАнулирован" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="logWrite" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="flagОжиданиеПроверки" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="idFileRegistProgect" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ФлагАнулирован" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ФлагВозвратНаДоработку" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ДатаПроверки" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProjectRegistrFiles" Member="ProjectRegistrFiles">
    <Type Name="ProjectRegistrFiles">
      <Column Name="IdProjectRegistr" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RegistrFileName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="NumberLatter" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="DateLetter" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="IdHospital" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="flagValidateRegistr" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="logWriteFIle" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DateWriteLetter" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ЛьготникAdd" Member="ЛьготникAdd">
    <Type Name="ЛьготникAdd">
      <Column Name="id_льготник" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Фамилия" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Имя" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Отчество" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="ДатаРождения" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="улица" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="НомерДома" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="корпус" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="НомерКвартиры" Type="System.String" DbType="NChar(40)" CanBeNull="true" />
      <Column Name="СерияПаспорта" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="НомерПаспорта" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="ДатаВыдачиПаспорта" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="КемВыданПаспорт" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="id_льготнойКатегории" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_документ" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="СерияДокумента" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="НомерДокумента" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="ДатаВыдачиДокумента" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="КемВыданДокумент" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="id_область" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_район" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_насПункт" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Снилс" Type="System.String" DbType="NVarChar(11)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ДоговорAdd" Member="ДоговорAdd">
    <Type Name="ДоговорAdd">
      <Column Name="id_договор" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="НомерДоговора" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="ДатаДоговора" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ДатаАктаВыполненныхРабот" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="СуммаАктаВыполненныхРабот" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="id_льготнаяКатегория" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_поликлинника" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Примечание" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="id_комитет" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ФлагНаличияДоговора" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ФлагНаличияАкта" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="id_льготник" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ФлагДопСоглашения" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="флагСРН" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="флагУслуги" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="датаВозврата" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ДатаЗаписиДоговора" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ФлагПроверки" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="НомерРеестра" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="ДатаРеестра" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="НомерСчётФактрура" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="ДатаСчётФактура" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="flagАнулирован" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="logWrite" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="flagОжиданиеПроверки" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="idFileRegistProgect" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ФлагАнулирован" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ФлагВозвратНаДоработку" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ДатаПроверки" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.УслугиПоДоговоруAdd" Member="УслугиПоДоговоруAdd">
    <Type Name="УслугиПоДоговоруAdd">
      <Column Name="id_услугиДоговор" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="НаименованиеУслуги" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="цена" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Количество" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_договор" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="НомерПоПеречню" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="Сумма" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ТехЛист" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Поликлинника" Member="Поликлинника">
    <Type Name="Поликлинника">
      <Column Name="id_поликлинника" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="НаименованиеПоликлинники" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="КодПоликлинники" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="ЮридическийАдрес" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ФактическийАдрес" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="id_главВрач" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_главБух" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="СвидетельствоРегистрации" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="ИНН" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="КПП" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="БИК" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="НаименованиеБанка" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="РасчётныйСчёт" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="ЛицевойСчёт" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="НомерЛицензии" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="ДатаРегистрацииЛицензии" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ОГРН" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="СвидетельствоРегистрацииЕГРЮЛ" Type="System.String" DbType="NChar(255)" CanBeNull="true" />
      <Column Name="ОрганВыдавшийЛицензию" Type="System.String" DbType="NChar(255)" CanBeNull="true" />
      <Column Name="Постановление" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ОКПО" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="ОКАТО" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="Flag" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="НачальныйНомерДоговора" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ПоликлинникиИнн" Member="ПоликлинникиИнн">
    <Type Name="ПоликлинникиИнн">
      <Column Name="F1" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="F2" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="F3" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="idRegion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LimitYearPiple" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Limit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SerialNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ТипДокумента" Member="ТипДокумента">
    <Type Name="ТипДокумента">
      <Column Name="id_документ" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="НаименованиеТипаДокумента" Type="System.String" DbType="NChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.УслугиПоДоговору" Member="УслугиПоДоговору">
    <Type Name="УслугиПоДоговору">
      <Column Name="id_услугиДоговор" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="НаименованиеУслуги" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="цена" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="Количество" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_договор" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="НомерПоПеречню" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="Сумма" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ТехЛист" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ViewPersonVipNet2" Member="ViewPersonVipNet2">
    <Type Name="ViewPersonVipNet2">
      <Column Name="Фамилия" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Имя" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="Отчество" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="ДатаРождения" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Улица" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="НомерДома" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Корпус" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="НомерКвартиры" Type="System.String" DbType="NChar(40)" CanBeNull="true" />
      <Column Name="id_район" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_насПункт" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NameRegion" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="Наименование" Type="System.String" DbType="NChar(250)" CanBeNull="true" />
      <Column Name="НомерАкта" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Column Name="ДатаАкта" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="ДатаПодписания" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.LimitMoney" Method="LimitMoney">
    <Parameter Name="Year" Parameter="year" Type="System.Int32" DbType="Int" />
    <Parameter Name="ЛьготнаяКатегория" Parameter="льготнаяКатегория" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="LimitMoneyResult">
      <Column Name="Limit" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.LimitMoney" Method="LimitMoney1">
    <Parameter Name="Year" Parameter="year" Type="System.Int32" DbType="Int" />
    <Parameter Name="ЛьготнаяКатегория" Parameter="льготнаяКатегория" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="LimitMoneyResult1">
      <Column Name="Limit" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.InsertResolution" Method="InsertResolution" IsComposable="true">
    <Parameter Name="nameResolution" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="date" Type="System.DateTime" DbType="Date" />
    <Return Type="object" />
  </Function>
</Database>